// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__AutoModePopUp() {
    GUI_Screen__AutoModePopUp = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__AutoModePopUp, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__AutoModePopUp__Set_parameters_aUTO_2 = lv_image_create(GUI_Screen__AutoModePopUp);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__Set_parameters_aUTO_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__Set_parameters_aUTO_2, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__AutoModePopUp__Set_parameters_aUTO_2, 800, 480);

    GUI_Container__AutoModePopUp__container_5 = lv_obj_create(GUI_Screen__AutoModePopUp);
    lv_obj_remove_style_all(GUI_Container__AutoModePopUp__container_5);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_5, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_5, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__AutoModePopUp__container_5, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__AutoModePopUp__container_5, -364, -2);
    lv_obj_set_size(GUI_Container__AutoModePopUp__container_5, 76, 482);

    GUI_Button__AutoModePopUp__button_12 = lv_button_create(GUI_Container__AutoModePopUp__container_5);
    lv_obj_set_align(GUI_Button__AutoModePopUp__button_12, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__AutoModePopUp__button_12, 4, -186);
    lv_obj_set_size(GUI_Button__AutoModePopUp__button_12, 76, 70);

    GUI_Image__AutoModePopUp__image_45 = lv_image_create(GUI_Button__AutoModePopUp__button_12);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image_45, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image_45, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image_45, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__AutoModePopUp__image_45, -16);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image_45, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_49 = lv_label_create(GUI_Button__AutoModePopUp__button_12);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_49, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_49, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Label__AutoModePopUp__label_49, 14);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_49, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__AutoModePopUp__button_11 = lv_button_create(GUI_Container__AutoModePopUp__container_5);
    lv_obj_set_align(GUI_Button__AutoModePopUp__button_11, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__AutoModePopUp__button_11, 2, -80);
    lv_obj_set_size(GUI_Button__AutoModePopUp__button_11, 76, 74);

    GUI_Label__AutoModePopUp__label_48 = lv_label_create(GUI_Button__AutoModePopUp__button_11);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_48, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_48, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Label__AutoModePopUp__label_48, 16);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_48, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__AutoModePopUp__image_44 = lv_image_create(GUI_Button__AutoModePopUp__button_11);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image_44, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image_44, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image_44, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__AutoModePopUp__image_44, -20);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image_44, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__AutoModePopUp__button_10 = lv_button_create(GUI_Container__AutoModePopUp__container_5);
    lv_obj_set_align(GUI_Button__AutoModePopUp__button_10, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__AutoModePopUp__button_10, 4, 46);
    lv_obj_set_size(GUI_Button__AutoModePopUp__button_10, 84, 90);

    GUI_Label__AutoModePopUp__label_47 = lv_label_create(GUI_Button__AutoModePopUp__button_10);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_47, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_47, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_47, -2, 14);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_47, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__AutoModePopUp__image_43 = lv_image_create(GUI_Button__AutoModePopUp__button_10);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image_43, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image_43, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image_43, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__AutoModePopUp__image_43, -2, -26);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image_43, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__AutoModePopUp__button_9 = lv_button_create(GUI_Container__AutoModePopUp__container_5);
    lv_obj_set_align(GUI_Button__AutoModePopUp__button_9, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Button__AutoModePopUp__button_9, 162);
    lv_obj_set_size(GUI_Button__AutoModePopUp__button_9, 76, 74);

    GUI_Label__AutoModePopUp__label_46 = lv_label_create(GUI_Button__AutoModePopUp__button_9);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_46, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_46, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Label__AutoModePopUp__label_46, 16);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_46, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__AutoModePopUp__image_42 = lv_image_create(GUI_Button__AutoModePopUp__button_9);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image_42, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image_42, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image_42, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__AutoModePopUp__image_42, -20);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image_42, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__AutoModePopUp__container_19 = lv_obj_create(GUI_Screen__AutoModePopUp);
    lv_obj_remove_style_all(GUI_Container__AutoModePopUp__container_19);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_19, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_19, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__AutoModePopUp__container_19, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__AutoModePopUp__container_19, 321, -210);
    lv_obj_set_size(GUI_Container__AutoModePopUp__container_19, 122, 48);

    GUI_Label__AutoModePopUp__label_55 = lv_label_create(GUI_Container__AutoModePopUp__container_19);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_55, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_55, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_55, 29, -2);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_55, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__AutoModePopUp__image_46 = lv_image_create(GUI_Container__AutoModePopUp__container_19);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image_46, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image_46, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image_46, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__AutoModePopUp__image_46, -24, -4);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image_46, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_58 = lv_label_create(GUI_Screen__AutoModePopUp);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_58, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_58, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_58, -220, 128);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_58, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_59 = lv_label_create(GUI_Screen__AutoModePopUp);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_59, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_59, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_59, -201, 127);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_59, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_86 = lv_label_create(GUI_Screen__AutoModePopUp);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_86, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_86, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_86, -39, 129);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_86, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_87 = lv_label_create(GUI_Screen__AutoModePopUp);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_87, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_87, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_87, -208, 193);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_87, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__AutoModePopUp__panel_6 = lv_obj_create(GUI_Screen__AutoModePopUp);
    lv_obj_remove_flag(GUI_Panel__AutoModePopUp__panel_6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__AutoModePopUp__panel_6, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__AutoModePopUp__panel_6, -2, 1);
    lv_obj_set_size(GUI_Panel__AutoModePopUp__panel_6, 800, 480);

    GUI_Container__AutoModePopUp__container_21 = lv_obj_create(GUI_Screen__AutoModePopUp);
    lv_obj_remove_style_all(GUI_Container__AutoModePopUp__container_21);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_21, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__AutoModePopUp__container_21, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__AutoModePopUp__container_21, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__AutoModePopUp__container_21, 8, 17);
    lv_obj_set_size(GUI_Container__AutoModePopUp__container_21, 452, 296);

    GUI_Label__AutoModePopUp__label_92 = lv_label_create(GUI_Container__AutoModePopUp__container_21);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_92, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_92, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_92, -2, -55);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_92, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__AutoModePopUp__AutoModePopUp_StartButton = lv_button_create(GUI_Container__AutoModePopUp__container_21);
    lv_obj_set_align(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton, 103, 103);
    lv_obj_set_size(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton, 158, 42);
    lv_obj_add_event_cb(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton,
                        GUI_event__Button__AutoModePopUp__AutoModePopUp_StartButton__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Label__AutoModePopUp__label_91 = lv_label_create(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_91, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_91, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_91, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton =
        lv_button_create(GUI_Container__AutoModePopUp__container_21);
    lv_obj_set_align(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton, -109, 103);
    lv_obj_set_size(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton, 152, 42);
    lv_obj_add_event_cb(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton,
                        GUI_event__Button__AutoModePopUp__AutoModePopUp_CancelButton__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Label__AutoModePopUp__label_90 = lv_label_create(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_90, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_90, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_90, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__AutoModePopUp__label_89 = lv_label_create(GUI_Container__AutoModePopUp__container_21);
    lv_label_set_long_mode(GUI_Label__AutoModePopUp__label_89, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__AutoModePopUp__label_89, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__AutoModePopUp__label_89, -4, 6);
    lv_obj_set_size(GUI_Label__AutoModePopUp__label_89, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__AutoModePopUp__image = lv_image_create(GUI_Container__AutoModePopUp__container_21);
    lv_obj_add_flag(GUI_Image__AutoModePopUp__image, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__AutoModePopUp__image, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__AutoModePopUp__image, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__AutoModePopUp__image, -6, -112);
    lv_obj_set_size(GUI_Image__AutoModePopUp__image, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__AutoModePopUp();
    GUI_initScreenTexts__AutoModePopUp();
}

void GUI_initScreenTexts__AutoModePopUp() {
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_49, "Home");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_48, "Set \nParameter");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_47, "WiFi \n");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_46, "Motor\nControl");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_55, "16:44");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_58, "30");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_59, "°C");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_86, "10% RH");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_87, "4 hours");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_92, "Start Incubation?");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_91, "Yes, Start");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_90, "Cancel");
    lv_label_set_text_static(GUI_Label__AutoModePopUp__label_89,
                             "Please confirm to start incubation \nwith current\nsettings.");
}

void GUI_initScreenStyles__AutoModePopUp() {
    lv_image_set_src(GUI_Image__AutoModePopUp__Set_parameters_aUTO_2, &upload_home_800x480_png);

    static lv_style_t GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT, 0);
    lv_style_set_bg_image_opa(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT, 255);
    lv_style_set_bg_image_src(&GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT,
                              &upload_vector_i1_582_24x17_png);
    lv_obj_add_style(GUI_Image__AutoModePopUp__Set_parameters_aUTO_2,
                     &GUI_Style__Image__AutoModePopUp__Set_parameters_aUTO_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__AutoModePopUp__button_12, &GUI_Style__Button__AutoModePopUp__button_12__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image_45, &upload_vector_i10_420_20x2250_png);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, lv_color_make(204, 193, 189));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, 171);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_49, &GUI_Style__Label__AutoModePopUp__label_49__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_text_letter_space(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__AutoModePopUp__button_11, &GUI_Style__Button__AutoModePopUp__button_11__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, lv_color_make(201, 113, 79));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, 171);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_48, &GUI_Style__Label__AutoModePopUp__label_48__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image_44, &upload_vector_i10_426_2512x25_png);

    static lv_style_t GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__AutoModePopUp__button_10, &GUI_Style__Button__AutoModePopUp__button_10__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, lv_color_make(204, 193, 189));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, 171);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_47, &GUI_Style__Label__AutoModePopUp__label_47__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image_43, &upload_vector_i7_437_30x2125_png);

    static lv_style_t GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_outline_color(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_text_letter_space(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__AutoModePopUp__button_9, &GUI_Style__Button__AutoModePopUp__button_9__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, lv_color_make(204, 193, 189));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, 171);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_46, &GUI_Style__Label__AutoModePopUp__label_46__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image_42, &upload_vector_i7_431_2750x20_png);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_55, &GUI_Style__Label__AutoModePopUp__label_55__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image_46, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_58, &GUI_Style__Label__AutoModePopUp__label_58__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_59, &GUI_Style__Label__AutoModePopUp__label_59__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_86, &GUI_Style__Label__AutoModePopUp__label_86__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT, lv_color_make(255, 251, 251));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_87, &GUI_Style__Label__AutoModePopUp__label_87__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, lv_color_make(33, 31, 31));
    lv_style_set_bg_opa(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, 173);
    lv_style_set_radius(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Panel__AutoModePopUp__panel_6, &GUI_Style__Panel__AutoModePopUp__panel_6__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT, 15);
    lv_obj_add_style(GUI_Container__AutoModePopUp__container_21,
                     &GUI_Style__Container__AutoModePopUp__container_21__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, &Montserrat_24_500);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_92, &GUI_Style__Label__AutoModePopUp__label_92__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_outline_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_pad_all(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__AutoModePopUp__AutoModePopUp_StartButton,
                     &GUI_Style__Button__AutoModePopUp__AutoModePopUp_StartButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_91, &GUI_Style__Label__AutoModePopUp__label_91__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 5);
    lv_style_set_outline_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_pad_all(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__AutoModePopUp__AutoModePopUp_CancelButton,
                     &GUI_Style__Button__AutoModePopUp__AutoModePopUp_CancelButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, 2);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_90, &GUI_Style__Label__AutoModePopUp__label_90__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, &Font);
    lv_style_set_text_color(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__AutoModePopUp__label_89, &GUI_Style__Label__AutoModePopUp__label_89__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__AutoModePopUp__image, &upload_si_warningfill_png);
}
