// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__Available_Networks() {
    GUI_Screen__Available_Networks = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__Available_Networks, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__Available_Networks__image_6 = lv_image_create(GUI_Screen__Available_Networks);
    lv_obj_add_flag(GUI_Image__Available_Networks__image_6, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__image_6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__image_6, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__Available_Networks__image_6, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Available_Networks__container_8 = lv_obj_create(GUI_Screen__Available_Networks);
    lv_obj_remove_style_all(GUI_Container__Available_Networks__container_8);
    lv_obj_remove_flag(GUI_Container__Available_Networks__container_8, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Available_Networks__container_8, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Available_Networks__container_8, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Available_Networks__container_8, 19, 17);
    lv_obj_set_size(GUI_Container__Available_Networks__container_8, 636, 382);

    GUI_Button__Available_Networks__AvailableNetworks1 =
        lv_button_create(GUI_Container__Available_Networks__container_8);
    lv_obj_set_align(GUI_Button__Available_Networks__AvailableNetworks1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__AvailableNetworks1, -7, -97);
    lv_obj_set_size(GUI_Button__Available_Networks__AvailableNetworks1, 588, 50);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__AvailableNetworks1,
                        GUI_event__Button__Available_Networks__AvailableNetworks1__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Available_Networks__image_13 = lv_image_create(GUI_Button__Available_Networks__AvailableNetworks1);
    lv_obj_add_flag(GUI_Image__Available_Networks__image_13, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__image_13, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__image_13, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__image_13, 252, 3);
    lv_obj_set_size(GUI_Image__Available_Networks__image_13, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Available_Networks__label = lv_label_create(GUI_Button__Available_Networks__AvailableNetworks1);
    lv_label_set_long_mode(GUI_Label__Available_Networks__label, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Available_Networks__label, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Available_Networks__label, -214, -1);
    lv_obj_set_size(GUI_Label__Available_Networks__label, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Available_Networks__AvailableNetworks2 =
        lv_button_create(GUI_Container__Available_Networks__container_8);
    lv_obj_set_align(GUI_Button__Available_Networks__AvailableNetworks2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__AvailableNetworks2, -9, -35);
    lv_obj_set_size(GUI_Button__Available_Networks__AvailableNetworks2, 590, 50);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__AvailableNetworks2,
                        GUI_event__Button__Available_Networks__AvailableNetworks2__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Available_Networks__image_16 = lv_image_create(GUI_Button__Available_Networks__AvailableNetworks2);
    lv_obj_add_flag(GUI_Image__Available_Networks__image_16, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__image_16, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__image_16, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__image_16, 233, -1);
    lv_obj_set_size(GUI_Image__Available_Networks__image_16, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Available_Networks__label_84 = lv_label_create(GUI_Button__Available_Networks__AvailableNetworks2);
    lv_label_set_long_mode(GUI_Label__Available_Networks__label_84, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Available_Networks__label_84, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Available_Networks__label_84, -215, -3);
    lv_obj_set_size(GUI_Label__Available_Networks__label_84, LV_SIZE_CONTENT, LV_SIZE_CONTENT); 

    GUI_Button__Available_Networks__AvailableNetworks3 =
        lv_button_create(GUI_Container__Available_Networks__container_8);
    lv_obj_set_align(GUI_Button__Available_Networks__AvailableNetworks3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__AvailableNetworks3, -9, 27);
    lv_obj_set_size(GUI_Button__Available_Networks__AvailableNetworks3, 590, 50);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__AvailableNetworks3,
                        GUI_event__Button__Available_Networks__AvailableNetworks3__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Available_Networks__image_17 = lv_image_create(GUI_Button__Available_Networks__AvailableNetworks3);
    lv_obj_add_flag(GUI_Image__Available_Networks__image_17, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__image_17, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__image_17, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__image_17, 256, 3);
    lv_obj_set_size(GUI_Image__Available_Networks__image_17, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Available_Networks__label_85 = lv_label_create(GUI_Button__Available_Networks__AvailableNetworks3);
    lv_label_set_long_mode(GUI_Label__Available_Networks__label_85, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Available_Networks__label_85, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Available_Networks__label_85, -214, 1);
    lv_obj_set_size(GUI_Label__Available_Networks__label_85, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Available_Networks__Label_3 = lv_label_create(GUI_Container__Available_Networks__container_8);
    lv_label_set_long_mode(GUI_Label__Available_Networks__Label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Available_Networks__Label_3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Available_Networks__Label_3, -224, -144);
    lv_obj_set_size(GUI_Label__Available_Networks__Label_3, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Available_Networks__Image_4 = lv_image_create(GUI_Screen__Available_Networks);
    lv_obj_add_flag(GUI_Image__Available_Networks__Image_4, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__Image_4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__Image_4, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__Image_4, 242, -79);
    lv_obj_set_size(GUI_Image__Available_Networks__Image_4, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Available_Networks__Image_5 = lv_image_create(GUI_Screen__Available_Networks);
    lv_obj_add_flag(GUI_Image__Available_Networks__Image_5, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__Image_5, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__Image_5, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__Image_5, 241, 47);
    lv_obj_set_size(GUI_Image__Available_Networks__Image_5, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Available_Networks__Container_14 = lv_obj_create(GUI_Screen__Available_Networks);
    lv_obj_remove_style_all(GUI_Container__Available_Networks__Container_14);
    lv_obj_remove_flag(GUI_Container__Available_Networks__Container_14, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Available_Networks__Container_14, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Available_Networks__Container_14, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Available_Networks__Container_14, -363, 1);
    lv_obj_set_size(GUI_Container__Available_Networks__Container_14, 70, 482);

    GUI_Button__Available_Networks__Button_28 = lv_button_create(GUI_Container__Available_Networks__Container_14);
    lv_obj_set_align(GUI_Button__Available_Networks__Button_28, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__Button_28, -2, -187);
    lv_obj_set_size(GUI_Button__Available_Networks__Button_28, 74, 64);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__Button_28,
                        GUI_event__Button__Available_Networks__Button_28__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Available_Networks__Button_27 = lv_button_create(GUI_Container__Available_Networks__Container_14);
    lv_obj_set_align(GUI_Button__Available_Networks__Button_27, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__Button_27, -1, -62);
    lv_obj_set_size(GUI_Button__Available_Networks__Button_27, 76, 64);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__Button_27,
                        GUI_event__Button__Available_Networks__Button_27__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Available_Networks__Button_26 = lv_button_create(GUI_Container__Available_Networks__Container_14);
    lv_obj_set_align(GUI_Button__Available_Networks__Button_26, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__Button_26, -1, 54);
    lv_obj_set_size(GUI_Button__Available_Networks__Button_26, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__Button_26,
                        GUI_event__Button__Available_Networks__Button_26__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Available_Networks__Button_25 = lv_button_create(GUI_Container__Available_Networks__Container_14);
    lv_obj_set_align(GUI_Button__Available_Networks__Button_25, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Available_Networks__Button_25, -2, 182);
    lv_obj_set_size(GUI_Button__Available_Networks__Button_25, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Available_Networks__Button_25,
                        GUI_event__Button__Available_Networks__Button_25__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Container__Available_Networks__container_18 = lv_obj_create(GUI_Screen__Available_Networks);
    lv_obj_remove_style_all(GUI_Container__Available_Networks__container_18);
    lv_obj_remove_flag(GUI_Container__Available_Networks__container_18, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Available_Networks__container_18, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Available_Networks__container_18, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Available_Networks__container_18, 328, -207);
    lv_obj_set_size(GUI_Container__Available_Networks__container_18, 122, 48);

    GUI_Label__Available_Networks__AutoMode_TIME_1 = lv_label_create(GUI_Container__Available_Networks__container_18);
    lv_label_set_long_mode(GUI_Label__Available_Networks__AutoMode_TIME_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Available_Networks__AutoMode_TIME_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Available_Networks__AutoMode_TIME_1, 31, -4);
    lv_obj_set_size(GUI_Label__Available_Networks__AutoMode_TIME_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Available_Networks__AutoMode_WIFI_image_1 =
    lv_image_create(GUI_Container__Available_Networks__container_18);
    lv_obj_add_flag(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, -24, -4);
    lv_obj_set_size(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Available_Networks__Image_15 = lv_image_create(GUI_Screen__Available_Networks);
    lv_obj_add_flag(GUI_Image__Available_Networks__Image_15, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Available_Networks__Image_15, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Available_Networks__Image_15, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Available_Networks__Image_15, -247, -168);
    lv_obj_set_size(GUI_Image__Available_Networks__Image_15, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__Available_Networks();
    GUI_initScreenTexts__Available_Networks();
}

void GUI_initScreenTexts__Available_Networks() {
    lv_label_set_text_static(GUI_Label__Available_Networks__label, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__Available_Networks__label_84, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__Available_Networks__label_85, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__Available_Networks__Label_3, "WiFi Networks");
    lv_label_set_text_static(GUI_Label__Available_Networks__AutoMode_TIME_1, "16:44");
}

void GUI_initScreenStyles__Available_Networks() {
    static lv_style_t GUI_Style__Screen__Available_Networks__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Screen__Available_Networks__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Screen__Available_Networks, &GUI_Style__Screen__Available_Networks__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__image_6, &upload_availablenetworks_png);

    static lv_style_t GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__Available_Networks__image_6,
                     &GUI_Style__Image__Available_Networks__image_6__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT);
    lv_style_set_border_color(&GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Container__Available_Networks__container_8,
                     &GUI_Style__Container__Available_Networks__container_8__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Available_Networks__AvailableNetworks1,
                     &GUI_Style__Button__Available_Networks__AvailableNetworks1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__image_13, &upload_frame_38_png);

    static lv_style_t GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, &Font);
    lv_style_set_text_color(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Available_Networks__label, &GUI_Style__Label__Available_Networks__label__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 255);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Available_Networks__AvailableNetworks2,
                     &GUI_Style__Button__Available_Networks__AvailableNetworks2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__image_16, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, &Font);
    lv_obj_add_style(GUI_Label__Available_Networks__label_84,
                     &GUI_Style__Label__Available_Networks__label_84__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 255);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Available_Networks__AvailableNetworks3,
                     &GUI_Style__Button__Available_Networks__AvailableNetworks3__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__image_17, &upload_frame_38_png);

    static lv_style_t GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, &Font);
    lv_obj_add_style(GUI_Label__Available_Networks__label_85,
                     &GUI_Style__Label__Available_Networks__label_85__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Available_Networks__Label_3,
                     &GUI_Style__Label__Available_Networks__Label_3__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__Image_4, &upload_vector_i1_582_24x17_png);

    lv_image_set_src(GUI_Image__Available_Networks__Image_5, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT,
                              lv_color_make(255, 193, 7));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT,
                               lv_color_make(255, 193, 7));
    lv_style_set_outline_opa(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_TOP);
    lv_style_set_pad_all(&GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, 11);
    lv_obj_add_style(GUI_Button__Available_Networks__Button_28,
                     &GUI_Style__Button__Available_Networks__Button_28__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Available_Networks__Button_27,
                     &GUI_Style__Button__Available_Networks__Button_27__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Available_Networks__Button_26,
                     &GUI_Style__Button__Available_Networks__Button_26__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Available_Networks__Button_25,
                     &GUI_Style__Button__Available_Networks__Button_25__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Available_Networks__AutoMode_TIME_1,
                     &GUI_Style__Label__Available_Networks__AutoMode_TIME_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Available_Networks__AutoMode_WIFI_image_1, &upload_vector_i1_582_24x17_png);

    lv_image_set_src(GUI_Image__Available_Networks__Image_15, &upload_group_3_png);
}
