// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__CustomModePopUp() {
    GUI_Screen__CustomModePopUp = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__CustomModePopUp, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__CustomModePopUp__image_47 = lv_image_create(GUI_Screen__CustomModePopUp);
    lv_obj_add_flag(GUI_Image__CustomModePopUp__image_47, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__CustomModePopUp__image_47, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__CustomModePopUp__image_47, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__CustomModePopUp__image_47, -1);
    lv_obj_set_size(GUI_Image__CustomModePopUp__image_47, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__CustomModePopUp__container_22 = lv_obj_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_style_all(GUI_Container__CustomModePopUp__container_22);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_22, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_22, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__CustomModePopUp__container_22, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__CustomModePopUp__container_22, -140, 12);
    lv_obj_set_size(GUI_Container__CustomModePopUp__container_22, 340, 334);

    GUI_Label__CustomModePopUp__label_96 = lv_label_create(GUI_Container__CustomModePopUp__container_22);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_96, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_96, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_96, -89, -138);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_96, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__CustomModePopUp__label_95 = lv_label_create(GUI_Container__CustomModePopUp__container_22);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_95, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_95, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_95, -103, -61);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_95, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__CustomModePopUp__label_94 = lv_label_create(GUI_Container__CustomModePopUp__container_22);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_94, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_94, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_94, -90, 18);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_94, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__CustomModePopUp__container_24 = lv_obj_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_style_all(GUI_Container__CustomModePopUp__container_24);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_24, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_24, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__CustomModePopUp__container_24, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__CustomModePopUp__container_24, 299, -215);
    lv_obj_set_size(GUI_Container__CustomModePopUp__container_24, 122, 48);

    GUI_Label__CustomModePopUp__label_100 = lv_label_create(GUI_Container__CustomModePopUp__container_24);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_100, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_100, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_100, 29, -2);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_100, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__CustomModePopUp__image_48 = lv_image_create(GUI_Container__CustomModePopUp__container_24);
    lv_obj_add_flag(GUI_Image__CustomModePopUp__image_48, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__CustomModePopUp__image_48, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__CustomModePopUp__image_48, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__CustomModePopUp__image_48, -24, -4);
    lv_obj_set_size(GUI_Image__CustomModePopUp__image_48, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__CustomModePopUp__panel_7 = lv_obj_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_flag(GUI_Panel__CustomModePopUp__panel_7, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__CustomModePopUp__panel_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__CustomModePopUp__panel_7, -359, 2);
    lv_obj_set_size(GUI_Panel__CustomModePopUp__panel_7, 88, 484);

    GUI_Keyboard__CustomModePopUp__keyboard_1 = lv_keyboard_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_flag(GUI_Keyboard__CustomModePopUp__keyboard_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(GUI_Keyboard__CustomModePopUp__keyboard_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_keyboard_set_mode(GUI_Keyboard__CustomModePopUp__keyboard_1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_align(GUI_Keyboard__CustomModePopUp__keyboard_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Keyboard__CustomModePopUp__keyboard_1, 208, 35);
    lv_obj_set_size(GUI_Keyboard__CustomModePopUp__keyboard_1, 272, 244);

    GUI_Panel__CustomModePopUp__panel_8 = lv_obj_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_flag(GUI_Panel__CustomModePopUp__panel_8, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__CustomModePopUp__panel_8, LV_ALIGN_CENTER);
    lv_obj_set_x(GUI_Panel__CustomModePopUp__panel_8, -1);
    lv_obj_set_size(GUI_Panel__CustomModePopUp__panel_8, 800, 480);

    GUI_Container__CustomModePopUp__container_26 = lv_obj_create(GUI_Screen__CustomModePopUp);
    lv_obj_remove_style_all(GUI_Container__CustomModePopUp__container_26);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_26, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__CustomModePopUp__container_26, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__CustomModePopUp__container_26, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__CustomModePopUp__container_26, -12, 16);
    lv_obj_set_size(GUI_Container__CustomModePopUp__container_26, 526, 394);

    GUI_Panel__CustomModePopUp__Panel = lv_obj_create(GUI_Container__CustomModePopUp__container_26);
    lv_obj_remove_flag(GUI_Panel__CustomModePopUp__Panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__CustomModePopUp__Panel, LV_ALIGN_CENTER);
    lv_obj_set_x(GUI_Panel__CustomModePopUp__Panel, 2);
    lv_obj_set_size(GUI_Panel__CustomModePopUp__Panel, 372, 280);

    GUI_Button__CustomModePopUp__CustomModePopUp_StartButton = lv_button_create(GUI_Panel__CustomModePopUp__Panel);
    lv_obj_set_align(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton, 86, 100);
    lv_obj_set_size(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton, 158, 42);
    lv_obj_add_event_cb(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton,
                        GUI_event__Button__CustomModePopUp__CustomModePopUp_StartButton__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Label__CustomModePopUp__label_107 = lv_label_create(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_107, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_107, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_107, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton = lv_button_create(GUI_Panel__CustomModePopUp__Panel);
    lv_obj_set_align(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton, -86, 98);
    lv_obj_set_size(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton, 152, 42);
    lv_obj_add_event_cb(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton,
                        GUI_event__Button__CustomModePopUp__CustomModePopUp_CancelButton__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Label__CustomModePopUp__label_106 = lv_label_create(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_106, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_106, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_106, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__CustomModePopUp__image_53 = lv_image_create(GUI_Panel__CustomModePopUp__Panel);
    lv_obj_add_flag(GUI_Image__CustomModePopUp__image_53, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__CustomModePopUp__image_53, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__CustomModePopUp__image_53, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__CustomModePopUp__image_53, -1, -91);
    lv_obj_set_size(GUI_Image__CustomModePopUp__image_53, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__CustomModePopUp__label_105 = lv_label_create(GUI_Panel__CustomModePopUp__Panel);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_105, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_105, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_105, -6, 6);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_105, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__CustomModePopUp__label_108 = lv_label_create(GUI_Panel__CustomModePopUp__Panel);
    lv_label_set_long_mode(GUI_Label__CustomModePopUp__label_108, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__CustomModePopUp__label_108, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__CustomModePopUp__label_108, 2, -51);
    lv_obj_set_size(GUI_Label__CustomModePopUp__label_108, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__CustomModePopUp();
    GUI_initScreenTexts__CustomModePopUp();
}

void GUI_initScreenTexts__CustomModePopUp() {
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_96, "Temperature ");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_95, "Humidity");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_94, "Turn Interval");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_100, "16:44");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_107, "Yes, Start");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_106, "Cancel");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_105,
                             "Please confirm to start\nincubation with current\nsettings.");
    lv_label_set_text_static(GUI_Label__CustomModePopUp__label_108, "Start Incubation?");
}

void GUI_initScreenStyles__CustomModePopUp() {
    lv_image_set_src(GUI_Image__CustomModePopUp__image_47, &upload_set_parametersmanual_png);

    static lv_style_t GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT);
    lv_style_set_border_color(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 0);
    lv_style_set_pad_all(&GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__CustomModePopUp__image_47, &GUI_Style__Image__CustomModePopUp__image_47__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_96, &GUI_Style__Label__CustomModePopUp__label_96__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_95, &GUI_Style__Label__CustomModePopUp__label_95__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_94, &GUI_Style__Label__CustomModePopUp__label_94__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_100, &GUI_Style__Label__CustomModePopUp__label_100__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__CustomModePopUp__image_48, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Panel__CustomModePopUp__panel_7, &GUI_Style__Panel__CustomModePopUp__panel_7__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Keyboard__CustomModePopUp__keyboard_1,
                     &GUI_Style__Keyboard__CustomModePopUp__keyboard_1__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, lv_color_make(33, 31, 31));
    lv_style_set_bg_opa(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, 173);
    lv_style_set_radius(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Panel__CustomModePopUp__panel_8, &GUI_Style__Panel__CustomModePopUp__panel_8__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Container__CustomModePopUp__container_26,
                     &GUI_Style__Container__CustomModePopUp__container_26__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT, 13);
    lv_obj_add_style(GUI_Button__CustomModePopUp__CustomModePopUp_StartButton,
                     &GUI_Style__Button__CustomModePopUp__CustomModePopUp_StartButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, lv_color_make(227, 221, 218));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT, &Font_2);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_107, &GUI_Style__Label__CustomModePopUp__label_107__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 13);
    lv_style_set_border_color(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_TOP);
    lv_style_set_shadow_color(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__CustomModePopUp__CustomModePopUp_CancelButton,
                     &GUI_Style__Button__CustomModePopUp__CustomModePopUp_CancelButton__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, 2);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_106, &GUI_Style__Label__CustomModePopUp__label_106__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__CustomModePopUp__image_53, &upload_si_warningfill_png);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, &Montserrat17Medium);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, 3);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, 5);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_105, &GUI_Style__Label__CustomModePopUp__label_105__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, &Montserrat_24_500);
    lv_style_set_text_color(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__CustomModePopUp__label_108, &GUI_Style__Label__CustomModePopUp__label_108__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
