// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__Home() {
    GUI_Screen__Home = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__Home, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__Home__Image_56 = lv_image_create(GUI_Screen__Home);
    lv_obj_add_flag(GUI_Image__Home__Image_56, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__Image_56, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__Image_56, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__Home__Image_56, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__Home__Ellipse_1 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_flag(GUI_Panel__Home__Ellipse_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__Home__Ellipse_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__Home__Ellipse_1, -131, -23);
    lv_obj_set_size(GUI_Panel__Home__Ellipse_1, 8, 8);

    GUI_Panel__Home__Ellipse_44 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_flag(GUI_Panel__Home__Ellipse_44, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__Home__Ellipse_44, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__Home__Ellipse_44, -270, -23);
    lv_obj_set_size(GUI_Panel__Home__Ellipse_44, 8, 8);

    GUI_Label__Home__SystemHealthDiagnostic_1 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__SystemHealthDiagnostic_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__SystemHealthDiagnostic_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__SystemHealthDiagnostic_1, -229, -23);
    lv_obj_set_size(GUI_Label__Home__SystemHealthDiagnostic_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Heater_Diagnostic_1 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Heater_Diagnostic_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Heater_Diagnostic_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Heater_Diagnostic_1, -228, 105);
    lv_obj_set_size(GUI_Label__Home__Heater_Diagnostic_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__Home__Ellipse_3 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_flag(GUI_Panel__Home__Ellipse_3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__Home__Ellipse_3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__Home__Ellipse_3, -140, 106);
    lv_obj_set_size(GUI_Panel__Home__Ellipse_3, 8, 8);

    GUI_Label__Home__Motor_Sensor_Diagnostic_1 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Motor_Sensor_Diagnostic_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Motor_Sensor_Diagnostic_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Motor_Sensor_Diagnostic_1, -98, 106);
    lv_obj_set_size(GUI_Label__Home__Motor_Sensor_Diagnostic_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__WaterLevel_Diagnostic_1 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__WaterLevel_Diagnostic_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__WaterLevel_Diagnostic_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__WaterLevel_Diagnostic_1, -99, -23);
    lv_obj_set_size(GUI_Label__Home__WaterLevel_Diagnostic_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Room_Humidity = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Room_Humidity, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Room_Humidity, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Room_Humidity, 251, -51);
    lv_obj_set_size(GUI_Label__Home__Room_Humidity, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Ttal_days = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Ttal_days, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Ttal_days, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Ttal_days, 97, 49);
    lv_obj_set_size(GUI_Label__Home__Ttal_days, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__SystemHealthDiagnostic_2 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__SystemHealthDiagnostic_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__SystemHealthDiagnostic_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__SystemHealthDiagnostic_2, -231, -8);
    lv_obj_set_size(GUI_Label__Home__SystemHealthDiagnostic_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__WaterLevel_Diagnostic_2 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__WaterLevel_Diagnostic_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__WaterLevel_Diagnostic_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__WaterLevel_Diagnostic_2, -100, -7);
    lv_obj_set_size(GUI_Label__Home__WaterLevel_Diagnostic_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Heater_Diagnostic_2 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Heater_Diagnostic_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Heater_Diagnostic_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Heater_Diagnostic_2, -231, 117);
    lv_obj_set_size(GUI_Label__Home__Heater_Diagnostic_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Home__container_2 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_style_all(GUI_Container__Home__container_2);
    lv_obj_remove_flag(GUI_Container__Home__container_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Home__container_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Home__container_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Home__container_2, 297, -215);
    lv_obj_set_size(GUI_Container__Home__container_2, 180, 44);

    GUI_Label__Home__HOME_TIMEimage = lv_label_create(GUI_Container__Home__container_2);
    lv_label_set_long_mode(GUI_Label__Home__HOME_TIMEimage, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__HOME_TIMEimage, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__HOME_TIMEimage, 42, -2);
    lv_obj_set_size(GUI_Label__Home__HOME_TIMEimage, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Home__HOME_WiFi_image = lv_image_create(GUI_Container__Home__container_2);
    lv_obj_add_flag(GUI_Image__Home__HOME_WiFi_image, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__HOME_WiFi_image, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__HOME_WiFi_image, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Home__HOME_WiFi_image, -12, -2);
    lv_obj_set_size(GUI_Image__Home__HOME_WiFi_image, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Home__container_16 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_style_all(GUI_Container__Home__container_16);
    lv_obj_remove_flag(GUI_Container__Home__container_16, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Home__container_16, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Home__container_16, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Home__container_16, -364, -2);
    lv_obj_set_size(GUI_Container__Home__container_16, 76, 482);

    GUI_Button__Home__Home_HOME_button = lv_button_create(GUI_Container__Home__container_16);
    lv_obj_set_align(GUI_Button__Home__Home_HOME_button, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Home__Home_HOME_button, 3, -186);
    lv_obj_set_size(GUI_Button__Home__Home_HOME_button, 84, 70);
    lv_obj_add_event_cb(GUI_Button__Home__Home_HOME_button, GUI_event__Button__Home__Home_HOME_button__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Image__Home__image_35 = lv_image_create(GUI_Button__Home__Home_HOME_button);
    lv_obj_add_flag(GUI_Image__Home__image_35, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__image_35, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__image_35, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__Home__image_35, -16);
    lv_obj_set_size(GUI_Image__Home__image_35, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Home__Image_23 = lv_image_create(GUI_Button__Home__Home_HOME_button);
    lv_obj_add_flag(GUI_Image__Home__Image_23, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__Image_23, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__Image_23, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Home__Image_23, -36, -4);
    lv_obj_set_size(GUI_Image__Home__Image_23, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__label_79 = lv_label_create(GUI_Button__Home__Home_HOME_button);
    lv_label_set_long_mode(GUI_Label__Home__label_79, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__label_79, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Label__Home__label_79, 14);
    lv_obj_set_size(GUI_Label__Home__label_79, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Home__Home_SET_PARAMETERS_button = lv_button_create(GUI_Container__Home__container_16);
    lv_obj_set_align(GUI_Button__Home__Home_SET_PARAMETERS_button, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Home__Home_SET_PARAMETERS_button, 2, -80);
    lv_obj_set_size(GUI_Button__Home__Home_SET_PARAMETERS_button, 76, 74);
    lv_obj_add_event_cb(GUI_Button__Home__Home_SET_PARAMETERS_button,
                        GUI_event__Button__Home__Home_SET_PARAMETERS_button__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Label__Home__label_5 = lv_label_create(GUI_Button__Home__Home_SET_PARAMETERS_button);
    lv_label_set_long_mode(GUI_Label__Home__label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__label_5, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__label_5, -3, 15);
    lv_obj_set_size(GUI_Label__Home__label_5, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Home__image_3 = lv_image_create(GUI_Button__Home__Home_SET_PARAMETERS_button);
    lv_obj_add_flag(GUI_Image__Home__image_3, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__image_3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__image_3, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__Home__image_3, -20);
    lv_obj_set_size(GUI_Image__Home__image_3, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Home__Home_WIFI_button = lv_button_create(GUI_Container__Home__container_16);
    lv_obj_set_align(GUI_Button__Home__Home_WIFI_button, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Button__Home__Home_WIFI_button, 40);
    lv_obj_set_size(GUI_Button__Home__Home_WIFI_button, 70, 82);
    lv_obj_add_event_cb(GUI_Button__Home__Home_WIFI_button, GUI_event__Button__Home__Home_WIFI_button__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Label__Home__label_2 = lv_label_create(GUI_Button__Home__Home_WIFI_button);
    lv_label_set_long_mode(GUI_Label__Home__label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__label_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__label_2, -2, 14);
    lv_obj_set_size(GUI_Label__Home__label_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Home__image_2 = lv_image_create(GUI_Button__Home__Home_WIFI_button);
    lv_obj_add_flag(GUI_Image__Home__image_2, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__image_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__image_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Home__image_2, -2, -26);
    lv_obj_set_size(GUI_Image__Home__image_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Home__Home_MOTORCONTROL_button = lv_button_create(GUI_Container__Home__container_16);
    lv_obj_set_align(GUI_Button__Home__Home_MOTORCONTROL_button, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Button__Home__Home_MOTORCONTROL_button, 162);
    lv_obj_set_size(GUI_Button__Home__Home_MOTORCONTROL_button, 76, 74);
    lv_obj_add_event_cb(GUI_Button__Home__Home_MOTORCONTROL_button,
                        GUI_event__Button__Home__Home_MOTORCONTROL_button__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Label__Home__label_1 = lv_label_create(GUI_Button__Home__Home_MOTORCONTROL_button);
    lv_label_set_long_mode(GUI_Label__Home__label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__label_1, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Label__Home__label_1, 16);
    lv_obj_set_size(GUI_Label__Home__label_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Home__image_1 = lv_image_create(GUI_Button__Home__Home_MOTORCONTROL_button);
    lv_obj_add_flag(GUI_Image__Home__image_1, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__image_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__image_1, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__Home__image_1, -20);
    lv_obj_set_size(GUI_Image__Home__image_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Label_7 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Label_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Label_7, 101, -51);
    lv_obj_set_size(GUI_Label__Home__Label_7, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Label_8 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Label_8, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Label_8, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Label_8, 256, 51);
    lv_obj_set_size(GUI_Label__Home__Label_8, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Label_9 = lv_label_create(GUI_Screen__Home);
    lv_label_set_long_mode(GUI_Label__Home__Label_9, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Label_9, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Label_9, 129, -51);
    lv_obj_set_size(GUI_Label__Home__Label_9, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Home__Button = lv_button_create(GUI_Screen__Home);
    lv_obj_set_align(GUI_Button__Home__Button, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Home__Button, 174, 124);
    lv_obj_set_size(GUI_Button__Home__Button, 210, 50);
    lv_obj_add_event_cb(GUI_Button__Home__Button, GUI_event__Button__Home__Button__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Home__Image_24 = lv_image_create(GUI_Button__Home__Button);
    lv_obj_add_flag(GUI_Image__Home__Image_24, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__Image_24, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__Image_24, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Home__Image_24, -74, 2);
    lv_obj_set_size(GUI_Image__Home__Image_24, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Home__Label_10 = lv_label_create(GUI_Button__Home__Button);
    lv_label_set_long_mode(GUI_Label__Home__Label_10, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Home__Label_10, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Home__Label_10, 16, 1);
    lv_obj_set_size(GUI_Label__Home__Label_10, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__Home__Ellipse_2 = lv_obj_create(GUI_Screen__Home);
    lv_obj_remove_flag(GUI_Panel__Home__Ellipse_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__Home__Ellipse_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Panel__Home__Ellipse_2, -269, 105);
    lv_obj_set_size(GUI_Panel__Home__Ellipse_2, 8, 8);

    GUI_Image__Home__Image_7 = lv_image_create(GUI_Screen__Home);
    lv_obj_add_flag(GUI_Image__Home__Image_7, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Home__Image_7, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Home__Image_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Home__Image_7, -247, -170);
    lv_obj_set_size(GUI_Image__Home__Image_7, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__Home();
    GUI_initScreenTexts__Home();
}

void GUI_initScreenTexts__Home() {
    lv_label_set_text_static(GUI_Label__Home__SystemHealthDiagnostic_1, "OPERATIONAL");
    lv_label_set_text_static(GUI_Label__Home__Heater_Diagnostic_1, "OPERATIONAL");
    lv_label_set_text_static(GUI_Label__Home__Motor_Sensor_Diagnostic_1, "OPERATIONAL");
    lv_label_set_text_static(GUI_Label__Home__WaterLevel_Diagnostic_1, "WARNING");
    lv_label_set_text_static(GUI_Label__Home__Room_Humidity, "7");
    lv_label_set_text_static(GUI_Label__Home__Ttal_days, "21");
    lv_label_set_text_static(GUI_Label__Home__SystemHealthDiagnostic_2, "All systems are Normal");
    lv_label_set_text_static(GUI_Label__Home__WaterLevel_Diagnostic_2, "Low Humidity");
    lv_label_set_text_static(GUI_Label__Home__Heater_Diagnostic_2, "Temperature Stable");
    lv_label_set_text_static(GUI_Label__Home__HOME_TIMEimage, "16:44");
    lv_label_set_text_static(GUI_Label__Home__label_79, "Home");
    lv_label_set_text_static(GUI_Label__Home__label_5, "Set \nParameter");
    lv_label_set_text_static(GUI_Label__Home__label_2, "WiFi \n");
    lv_label_set_text_static(GUI_Label__Home__label_1, "Motor\nControl");
    lv_label_set_text_static(GUI_Label__Home__Label_7, "30");
    lv_label_set_text_static(GUI_Label__Home__Label_8, "30");
    lv_label_set_text_static(GUI_Label__Home__Label_9, "%");
    lv_label_set_text_static(GUI_Label__Home__Label_10, "Stop Incubation");
}

void GUI_initScreenStyles__Home() {
    static lv_style_t GUI_Style__Screen__Home__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__Home__MAIN_DEFAULT);
    lv_style_set_shadow_color(&GUI_Style__Screen__Home__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Screen__Home__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Screen__Home__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Screen__Home__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Screen__Home__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Screen__Home__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Screen__Home__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Screen__Home__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Screen__Home__MAIN_DEFAULT, 2);
    lv_style_set_outline_pad(&GUI_Style__Screen__Home__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__Home, &GUI_Style__Screen__Home__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__Image_56, &upload_dash_20_png);

    static lv_style_t GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, 4);
    lv_style_set_outline_color(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_outline_opa(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, 1);
    lv_style_set_outline_pad(&GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Panel__Home__Ellipse_1, &GUI_Style__Panel__Home__Ellipse_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_bg_opa(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, 4);
    lv_style_set_outline_color(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_outline_opa(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, 1);
    lv_style_set_outline_pad(&GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Panel__Home__Ellipse_44, &GUI_Style__Panel__Home__Ellipse_44__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, &Font_1);
    lv_style_set_text_color(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT,
                            lv_color_make(76, 175, 80));
    lv_style_set_text_opa(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__SystemHealthDiagnostic_1,
                     &GUI_Style__Label__Home__SystemHealthDiagnostic_1__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT, &Font_1);
    lv_obj_add_style(GUI_Label__Home__Heater_Diagnostic_1, &GUI_Style__Label__Home__Heater_Diagnostic_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_bg_opa(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, 4);
    lv_style_set_outline_color(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_outline_opa(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT, 1);
    lv_obj_add_style(GUI_Panel__Home__Ellipse_3, &GUI_Style__Panel__Home__Ellipse_3__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT,
                            lv_color_make(23, 185, 28));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, &Font_1);
    lv_obj_add_style(GUI_Label__Home__Motor_Sensor_Diagnostic_1,
                     &GUI_Style__Label__Home__Motor_Sensor_Diagnostic_1__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_text_opa(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, &Font_1);
    lv_obj_add_style(GUI_Label__Home__WaterLevel_Diagnostic_1,
                     &GUI_Style__Label__Home__WaterLevel_Diagnostic_1__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT, &Montserrat_24_500);
    lv_obj_add_style(GUI_Label__Home__Room_Humidity, &GUI_Style__Label__Home__Room_Humidity__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT, &Montserrat_24_500);
    lv_obj_add_style(GUI_Label__Home__Ttal_days, &GUI_Style__Label__Home__Ttal_days__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, &Font_1);
    lv_style_set_text_color(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__SystemHealthDiagnostic_2,
                     &GUI_Style__Label__Home__SystemHealthDiagnostic_2__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, &Font_1);
    lv_obj_add_style(GUI_Label__Home__WaterLevel_Diagnostic_2,
                     &GUI_Style__Label__Home__WaterLevel_Diagnostic_2__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT, &Font_1);
    lv_obj_add_style(GUI_Label__Home__Heater_Diagnostic_2, &GUI_Style__Label__Home__Heater_Diagnostic_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__HOME_TIMEimage, &GUI_Style__Label__Home__HOME_TIMEimage__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__HOME_WiFi_image, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Home__Home_HOME_button, &GUI_Style__Button__Home__Home_HOME_button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__image_35, &upload_vector_i6_423_20x2250_png);

    lv_image_set_src(GUI_Image__Home__Image_23, &upload_rectangle_11_png);

    static lv_style_t GUI_Style__Label__Home__label_79__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, &Font_3);
    lv_style_set_text_color(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__label_79__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__label_79, &GUI_Style__Label__Home__label_79__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                            lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_text_letter_space(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_bg_color(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Home__Home_SET_PARAMETERS_button,
                     &GUI_Style__Button__Home__Home_SET_PARAMETERS_button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__label_5__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, &Font_3);
    lv_style_set_text_color(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, 171);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__label_5__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__Home__label_5, &GUI_Style__Label__Home__label_5__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__image_3, &upload_vector_i10_426_2512x25_png);

    static lv_style_t GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Home__Home_WIFI_button, &GUI_Style__Button__Home__Home_WIFI_button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__label_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, &Font_3);
    lv_style_set_text_color(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__label_2__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__Home__label_2, &GUI_Style__Label__Home__label_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__image_2, &upload_vector_i7_437_30x2125_png);

    static lv_style_t GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_outline_color(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_text_letter_space(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT,
                            lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Home__Home_MOTORCONTROL_button,
                     &GUI_Style__Button__Home__Home_MOTORCONTROL_button__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__label_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, 171);
    lv_style_set_text_font(&GUI_Style__Label__Home__label_1__MAIN_DEFAULT, &Font_3);
    lv_obj_add_style(GUI_Label__Home__label_1, &GUI_Style__Label__Home__label_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__image_1, &upload_vector_i7_431_2750x20_png);

    static lv_style_t GUI_Style__Label__Home__Label_7__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, &Montserrat_24_500);
    lv_style_set_text_color(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Label_7__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__Label_7, &GUI_Style__Label__Home__Label_7__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Label_8__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Label_8__MAIN_DEFAULT, &Montserrat_24_500);
    lv_obj_add_style(GUI_Label__Home__Label_8, &GUI_Style__Label__Home__Label_8__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Home__Label_9__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__Home__Label_9__MAIN_DEFAULT, &Montserrat_24_500);
    lv_obj_add_style(GUI_Label__Home__Label_9, &GUI_Style__Label__Home__Label_9__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Home__Button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Home__Button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Home__Button__MAIN_DEFAULT, lv_color_make(244, 67, 54));
    lv_style_set_bg_opa(&GUI_Style__Button__Home__Button__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__Home__Button__MAIN_DEFAULT, 13);
    lv_obj_add_style(GUI_Button__Home__Button, &GUI_Style__Button__Home__Button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__Image_24, &upload_vector_1_png);

    static lv_style_t GUI_Style__Label__Home__Label_10__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, &Montserrat17Medium);
    lv_style_set_text_color(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Home__Label_10__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Home__Label_10, &GUI_Style__Label__Home__Label_10__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_bg_opa(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, 4);
    lv_style_set_outline_color(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, lv_color_make(76, 175, 80));
    lv_style_set_outline_opa(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT, 1);
    lv_obj_add_style(GUI_Panel__Home__Ellipse_2, &GUI_Style__Panel__Home__Ellipse_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Home__Image_7, &upload_group_3_png);
}
