// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__MotorControl() {
    GUI_Screen__MotorControl = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__MotorControl, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__MotorControl__image_18 = lv_image_create(GUI_Screen__MotorControl);
    lv_obj_add_flag(GUI_Image__MotorControl__image_18, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__MotorControl__image_18, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__MotorControl__image_18, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__MotorControl__image_18, 1);
    lv_obj_set_size(GUI_Image__MotorControl__image_18, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__MotorControl__container_10 = lv_obj_create(GUI_Screen__MotorControl);
    lv_obj_remove_style_all(GUI_Container__MotorControl__container_10);
    lv_obj_remove_flag(GUI_Container__MotorControl__container_10, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__MotorControl__container_10, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__MotorControl__container_10, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__MotorControl__container_10, 27, 56);
    lv_obj_set_size(GUI_Container__MotorControl__container_10, 640, 340);

    GUI_Arc__MotorControl__arc_1 = lv_arc_create(GUI_Container__MotorControl__container_10);
    lv_arc_set_bg_angles(GUI_Arc__MotorControl__arc_1, 120, 60);
    lv_arc_set_mode(GUI_Arc__MotorControl__arc_1, LV_ARC_MODE_REVERSE);
    lv_arc_set_value(GUI_Arc__MotorControl__arc_1, 50);
    lv_obj_set_align(GUI_Arc__MotorControl__arc_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Arc__MotorControl__arc_1, 170, -94);
    lv_obj_set_size(GUI_Arc__MotorControl__arc_1, 132, 122);
    lv_obj_add_event_cb(GUI_Arc__MotorControl__arc_1, GUI_event__Arc__MotorControl__arc_1__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Arc__MotorControl__arc = lv_arc_create(GUI_Container__MotorControl__container_10);
    lv_arc_set_bg_angles(GUI_Arc__MotorControl__arc, 120, 60);
    lv_arc_set_mode(GUI_Arc__MotorControl__arc, LV_ARC_MODE_NORMAL);
    lv_arc_set_range(GUI_Arc__MotorControl__arc, 0, 100);
    lv_arc_set_rotation(GUI_Arc__MotorControl__arc, 0);
    lv_arc_set_value(GUI_Arc__MotorControl__arc, 23);
    lv_obj_set_align(GUI_Arc__MotorControl__arc, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Arc__MotorControl__arc, -148, -93);
    lv_obj_set_size(GUI_Arc__MotorControl__arc, 132, 122);
    lv_obj_add_event_cb(GUI_Arc__MotorControl__arc, GUI_event__Arc__MotorControl__arc__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Switch__MotorControl__Switch = lv_switch_create(GUI_Container__MotorControl__container_10);
    lv_obj_add_state(GUI_Switch__MotorControl__Switch, LV_STATE_PRESSED);
    _ui_clear_transition(GUI_Switch__MotorControl__Switch);
    lv_obj_set_align(GUI_Switch__MotorControl__Switch, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Switch__MotorControl__Switch, 193, 128);
    lv_obj_set_size(GUI_Switch__MotorControl__Switch, 88, 33);

    GUI_Switch__MotorControl__Switch_1 = lv_switch_create(GUI_Container__MotorControl__container_10);
    lv_obj_set_align(GUI_Switch__MotorControl__Switch_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Switch__MotorControl__Switch_1, -129, 130);
    lv_obj_set_size(GUI_Switch__MotorControl__Switch_1, 88, 33);

    GUI_Container__MotorControl__container_11 = lv_obj_create(GUI_Screen__MotorControl);
    lv_obj_remove_style_all(GUI_Container__MotorControl__container_11);
    lv_obj_remove_flag(GUI_Container__MotorControl__container_11, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__MotorControl__container_11, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__MotorControl__container_11, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__MotorControl__container_11, 299, -215);
    lv_obj_set_size(GUI_Container__MotorControl__container_11, 122, 48);

    GUI_Label__MotorControl__MotorControl_Time = lv_label_create(GUI_Container__MotorControl__container_11);
    lv_label_set_long_mode(GUI_Label__MotorControl__MotorControl_Time, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__MotorControl__MotorControl_Time, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__MotorControl__MotorControl_Time, 29, -2);
    lv_obj_set_size(GUI_Label__MotorControl__MotorControl_Time, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__MotorControl__MotorControl_Wifi = lv_image_create(GUI_Container__MotorControl__container_11);
    lv_obj_add_flag(GUI_Image__MotorControl__MotorControl_Wifi, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__MotorControl__MotorControl_Wifi, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__MotorControl__MotorControl_Wifi, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__MotorControl__MotorControl_Wifi, -24, -4);
    lv_obj_set_size(GUI_Image__MotorControl__MotorControl_Wifi, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__MotorControl__Container_17 = lv_obj_create(GUI_Screen__MotorControl);
    lv_obj_remove_style_all(GUI_Container__MotorControl__Container_17);
    lv_obj_remove_flag(GUI_Container__MotorControl__Container_17, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__MotorControl__Container_17, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__MotorControl__Container_17, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__MotorControl__Container_17, -364, 1);
    lv_obj_set_size(GUI_Container__MotorControl__Container_17, 70, 482);

    GUI_Button__MotorControl__Button_32 = lv_button_create(GUI_Container__MotorControl__Container_17);
    lv_obj_set_align(GUI_Button__MotorControl__Button_32, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_32, -2, -187);
    lv_obj_set_size(GUI_Button__MotorControl__Button_32, 74, 64);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_32, GUI_event__Button__MotorControl__Button_32__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Button__MotorControl__Button_31 = lv_button_create(GUI_Container__MotorControl__Container_17);
    lv_obj_set_align(GUI_Button__MotorControl__Button_31, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_31, -1, -62);
    lv_obj_set_size(GUI_Button__MotorControl__Button_31, 76, 64);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_31, GUI_event__Button__MotorControl__Button_31__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Button__MotorControl__Button_30 = lv_button_create(GUI_Container__MotorControl__Container_17);
    lv_obj_set_align(GUI_Button__MotorControl__Button_30, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_30, -1, 54);
    lv_obj_set_size(GUI_Button__MotorControl__Button_30, 70, 64);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_30, GUI_event__Button__MotorControl__Button_30__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Button__MotorControl__Button_29 = lv_button_create(GUI_Container__MotorControl__Container_17);
    lv_obj_set_align(GUI_Button__MotorControl__Button_29, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_29, -2, 184);
    lv_obj_set_size(GUI_Button__MotorControl__Button_29, 70, 64);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_29, GUI_event__Button__MotorControl__Button_29__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Button__MotorControl__Button_33 = lv_button_create(GUI_Screen__MotorControl);
    lv_obj_set_align(GUI_Button__MotorControl__Button_33, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_33, -129, 55);
    lv_obj_set_size(GUI_Button__MotorControl__Button_33, 200, 38);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_33, GUI_event__Button__MotorControl__Button_33__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Button__MotorControl__Button_34 = lv_button_create(GUI_Screen__MotorControl);
    lv_obj_set_align(GUI_Button__MotorControl__Button_34, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__MotorControl__Button_34, 191, 55);
    lv_obj_set_size(GUI_Button__MotorControl__Button_34, 200, 36);
    lv_obj_add_event_cb(GUI_Button__MotorControl__Button_34, GUI_event__Button__MotorControl__Button_34__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_initScreenStyles__MotorControl();
    GUI_initScreenTexts__MotorControl();
}

void GUI_initScreenTexts__MotorControl() {
    lv_label_set_text_static(GUI_Label__MotorControl__MotorControl_Time, "16:44");
}

void GUI_initScreenStyles__MotorControl() {
    static lv_style_t GUI_Style__Screen__MotorControl__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__MotorControl__MAIN_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Screen__MotorControl__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_arc_opa(&GUI_Style__Screen__MotorControl__MAIN_DEFAULT, 255);
    lv_style_set_arc_rounded(&GUI_Style__Screen__MotorControl__MAIN_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Screen__MotorControl__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Screen__MotorControl, &GUI_Style__Screen__MotorControl__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT;
    lv_style_init(&GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT, lv_color_make(62, 63, 136));
    lv_style_set_bg_opa(&GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT, 102);
    lv_style_set_radius(&GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT, 32767);
    lv_obj_add_style(GUI_Screen__MotorControl, &GUI_Style__Screen__MotorControl__SCROLLBAR_DEFAULT,
                     LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__MotorControl__image_18, &upload_manual_turn_png);

    static lv_style_t GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT);
    lv_style_set_border_color(&GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Container__MotorControl__container_10,
                     &GUI_Style__Container__MotorControl__container_10__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT, 255);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT, 10);
    lv_obj_add_style(GUI_Arc__MotorControl__arc_1, &GUI_Style__Arc__MotorControl__arc_1__INDICATOR_DEFAULT,
                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, 255);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, false);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, 15);
    lv_style_set_bg_color(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT, 0);
    lv_obj_add_style(GUI_Arc__MotorControl__arc_1, &GUI_Style__Arc__MotorControl__arc_1__KNOB_DEFAULT,
                     LV_PART_KNOB | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT, lv_color_make(208, 201, 196));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT, 133);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Arc__MotorControl__arc_1, &GUI_Style__Arc__MotorControl__arc_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, 255);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, 10);
    lv_style_set_bg_color(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, lv_color_make(204, 120, 92));
    lv_style_set_bg_opa(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT, 0);
    lv_obj_add_style(GUI_Arc__MotorControl__arc, &GUI_Style__Arc__MotorControl__arc__INDICATOR_DEFAULT,
                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, 0);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, 8);
    lv_style_set_bg_color(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT, 0);
    lv_obj_add_style(GUI_Arc__MotorControl__arc, &GUI_Style__Arc__MotorControl__arc__KNOB_DEFAULT,
                     LV_PART_KNOB | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT);
    lv_style_set_arc_color(&GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT, lv_color_make(208, 201, 196));
    lv_style_set_arc_opa(&GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT, 133);
    lv_style_set_arc_rounded(&GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT, true);
    lv_style_set_arc_width(&GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Arc__MotorControl__arc, &GUI_Style__Arc__MotorControl__arc__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch, &GUI_Style__Switch__MotorControl__Switch__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch, &GUI_Style__Switch__MotorControl__Switch__INDICATOR_DEFAULT,
                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch, &GUI_Style__Switch__MotorControl__Switch__MAIN_PRESSED,
                     LV_PART_MAIN | LV_STATE_PRESSED);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch, &GUI_Style__Switch__MotorControl__Switch__INDICATOR_PRESSED,
                     LV_PART_INDICATOR | LV_STATE_PRESSED);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED, lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch, &GUI_Style__Switch__MotorControl__Switch__KNOB_PRESSED,
                     LV_PART_KNOB | LV_STATE_PRESSED);

    static lv_style_t GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT, lv_color_make(116, 176, 146));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch_1, &GUI_Style__Switch__MotorControl__Switch_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch_1, &GUI_Style__Switch__MotorControl__Switch_1__INDICATOR_DEFAULT,
                     LV_PART_INDICATOR | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT;
    lv_style_init(&GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT, 32767);
    lv_obj_add_style(GUI_Switch__MotorControl__Switch_1, &GUI_Style__Switch__MotorControl__Switch_1__KNOB_DEFAULT,
                     LV_PART_KNOB | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Label__MotorControl__MotorControl_Time,
                     &GUI_Style__Label__MotorControl__MotorControl_Time__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__MotorControl__MotorControl_Wifi, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_outline_opa(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_TOP);
    lv_style_set_pad_all(&GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT, 11);
    lv_obj_add_style(GUI_Button__MotorControl__Button_32, &GUI_Style__Button__MotorControl__Button_32__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__MotorControl__Button_31, &GUI_Style__Button__MotorControl__Button_31__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__MotorControl__Button_30, &GUI_Style__Button__MotorControl__Button_30__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__MotorControl__Button_29, &GUI_Style__Button__MotorControl__Button_29__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__MotorControl__Button_33, &GUI_Style__Button__MotorControl__Button_33__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__MotorControl__Button_34, &GUI_Style__Button__MotorControl__Button_34__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
 