// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__PaswordInputPopUp() {
    GUI_Screen__PaswordInputPopUp = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__PaswordInputPopUp, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__PaswordInputPopUp__image_25 = lv_image_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_add_flag(GUI_Image__PaswordInputPopUp__image_25, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__PaswordInputPopUp__image_25, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__PaswordInputPopUp__image_25, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__PaswordInputPopUp__image_25, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__PaswordInputPopUp__container_3 = lv_obj_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_remove_style_all(GUI_Container__PaswordInputPopUp__container_3);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__PaswordInputPopUp__container_3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__PaswordInputPopUp__container_3, 39, 37);
    lv_obj_set_size(GUI_Container__PaswordInputPopUp__container_3, 636, 382);

    GUI_Button__PaswordInputPopUp__AvailableNetworks1_1 =
        lv_button_create(GUI_Container__PaswordInputPopUp__container_3);
    lv_obj_set_align(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1, -7, -97);
    lv_obj_set_size(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1, 588, 50);

    GUI_Image__PaswordInputPopUp__image_11 = lv_image_create(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1);
    lv_obj_add_flag(GUI_Image__PaswordInputPopUp__image_11, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__PaswordInputPopUp__image_11, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__PaswordInputPopUp__image_11, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__PaswordInputPopUp__image_11, 252, 3);
    lv_obj_set_size(GUI_Image__PaswordInputPopUp__image_11, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__PaswordInputPopUp__label_16 = lv_label_create(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_16, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_16, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__label_16, -214, -1);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_16, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__PaswordInputPopUp__AvailableNetworks2_1 =
        lv_button_create(GUI_Container__PaswordInputPopUp__container_3);
    lv_obj_set_align(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1, -9, -35);
    lv_obj_set_size(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1, 590, 50);

    GUI_Image__PaswordInputPopUp__image_10 = lv_image_create(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1);
    lv_obj_add_flag(GUI_Image__PaswordInputPopUp__image_10, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__PaswordInputPopUp__image_10, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__PaswordInputPopUp__image_10, LV_ALIGN_CENTER);
    lv_obj_set_x(GUI_Image__PaswordInputPopUp__image_10, 245);
    lv_obj_set_size(GUI_Image__PaswordInputPopUp__image_10, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__PaswordInputPopUp__label_15 = lv_label_create(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_15, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_15, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__label_15, -215, -3);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_15, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__PaswordInputPopUp__AvailableNetworks3_1 =
        lv_button_create(GUI_Container__PaswordInputPopUp__container_3);
    lv_obj_set_align(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1, -9, 27);
    lv_obj_set_size(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1, 590, 50);

    GUI_Image__PaswordInputPopUp__image_8 = lv_image_create(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1);
    lv_obj_add_flag(GUI_Image__PaswordInputPopUp__image_8, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__PaswordInputPopUp__image_8, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__PaswordInputPopUp__image_8, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__PaswordInputPopUp__image_8, 256, 3);
    lv_obj_set_size(GUI_Image__PaswordInputPopUp__image_8, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__PaswordInputPopUp__label_14 = lv_label_create(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_14, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_14, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__label_14, -214, 1);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_14, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__PaswordInputPopUp__Label_13 = lv_label_create(GUI_Container__PaswordInputPopUp__container_3);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__Label_13, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__Label_13, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__Label_13, -224, -144);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__Label_13, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Panel__PaswordInputPopUp__panel_2 = lv_obj_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_remove_flag(GUI_Panel__PaswordInputPopUp__panel_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Panel__PaswordInputPopUp__panel_2, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Panel__PaswordInputPopUp__panel_2, 806, 486);

    GUI_Container__PaswordInputPopUp__container_20 = lv_obj_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_remove_style_all(GUI_Container__PaswordInputPopUp__container_20);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_20, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_20, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__PaswordInputPopUp__container_20, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__PaswordInputPopUp__container_20, 318, -209);
    lv_obj_set_size(GUI_Container__PaswordInputPopUp__container_20, 122, 48);

    GUI_Label__PaswordInputPopUp__AutoMode_TIME_2 = lv_label_create(GUI_Container__PaswordInputPopUp__container_20);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2, 31, -4);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2 =
        lv_image_create(GUI_Container__PaswordInputPopUp__container_20);
    lv_obj_add_flag(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, -24, -4);
    lv_obj_set_size(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__PaswordInputPopUp__container_15 = lv_obj_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_remove_style_all(GUI_Container__PaswordInputPopUp__container_15);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_15, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__PaswordInputPopUp__container_15, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__PaswordInputPopUp__container_15, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__PaswordInputPopUp__container_15, -2, -107);
    lv_obj_set_size(GUI_Container__PaswordInputPopUp__container_15, 362, 210);

    GUI_Label__PaswordInputPopUp__label_75 = lv_label_create(GUI_Container__PaswordInputPopUp__container_15);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_75, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_75, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__label_75, -48, -75);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_75, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button =
        lv_button_create(GUI_Container__PaswordInputPopUp__container_15);
    lv_obj_set_align(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button, 83, 71);
    lv_obj_set_size(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button, 158, 42);
    lv_obj_add_event_cb(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button,
                        GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__Clicked,
                        LV_EVENT_CLICKED, NULL);

    GUI_Label__PaswordInputPopUp__label_77 =
        lv_label_create(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_77, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_77, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_77, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel =
        lv_button_create(GUI_Container__PaswordInputPopUp__container_15);
    lv_obj_set_align(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel, -83, 71);
    lv_obj_set_size(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel, 152, 42);
    lv_obj_add_event_cb(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel,
                        GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Label__PaswordInputPopUp__label_76 =
        lv_label_create(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__label_76, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__label_76, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__label_76, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__PaswordInputPopUp__Label_21 = lv_label_create(GUI_Container__PaswordInputPopUp__container_15);
    lv_label_set_long_mode(GUI_Label__PaswordInputPopUp__Label_21, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__PaswordInputPopUp__Label_21, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__PaswordInputPopUp__Label_21, -102, -32);
    lv_obj_set_size(GUI_Label__PaswordInputPopUp__Label_21, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Textarea__PaswordInputPopUp__Textarea_4 = lv_textarea_create(GUI_Container__PaswordInputPopUp__container_15);
    lv_textarea_set_text(GUI_Textarea__PaswordInputPopUp__Textarea_4, "");
    lv_textarea_set_password_mode(GUI_Textarea__PaswordInputPopUp__Textarea_4, true);
    lv_obj_set_align(GUI_Textarea__PaswordInputPopUp__Textarea_4, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Textarea__PaswordInputPopUp__Textarea_4, 270, 42);
    lv_obj_add_event_cb(GUI_Textarea__PaswordInputPopUp__Textarea_4,
                        GUI_event__Textarea__PaswordInputPopUp__Textarea_4__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Keyboard__PaswordInputPopUp__Keyboard = lv_keyboard_create(GUI_Screen__PaswordInputPopUp);
    lv_obj_remove_flag(GUI_Keyboard__PaswordInputPopUp__Keyboard, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(GUI_Keyboard__PaswordInputPopUp__Keyboard, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_set_align(GUI_Keyboard__PaswordInputPopUp__Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Keyboard__PaswordInputPopUp__Keyboard, 27, 123);
    lv_obj_set_size(GUI_Keyboard__PaswordInputPopUp__Keyboard, 664, 220);
    lv_obj_add_event_cb(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                        GUI_event__Keyboard__PaswordInputPopUp__Keyboard__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_initScreenStyles__PaswordInputPopUp();
    GUI_initScreenTexts__PaswordInputPopUp();
}

void GUI_initScreenTexts__PaswordInputPopUp() {
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_16, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_15, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_14, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__Label_13, "WiFi Networks");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2, "16:44");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_75, "Skill G Innovation");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_77, "Connect");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__label_76, "Cancel");
    lv_label_set_text_static(GUI_Label__PaswordInputPopUp__Label_21, "Password");
}

void GUI_initScreenStyles__PaswordInputPopUp() {
    lv_image_set_src(GUI_Image__PaswordInputPopUp__image_25, &upload_availablenetworks_png);

    static lv_style_t GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, 0);
    lv_style_set_bg_image_src(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT,
                              &upload_availablenetworks_png);
    lv_style_set_bg_image_opa(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, 255);
    lv_style_set_blend_mode(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, LV_BLEND_MODE_NORMAL);
    lv_style_set_opa(&GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, 255);
    lv_obj_add_style(GUI_Image__PaswordInputPopUp__image_25,
                     &GUI_Style__Image__PaswordInputPopUp__image_25__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT);
    lv_style_set_border_color(&GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Container__PaswordInputPopUp__container_3,
                     &GUI_Style__Container__PaswordInputPopUp__container_3__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__PaswordInputPopUp__AvailableNetworks1_1,
                     &GUI_Style__Button__PaswordInputPopUp__AvailableNetworks1_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__PaswordInputPopUp__image_11, &upload_frame_38_png);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, &Font);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_16,
                     &GUI_Style__Label__PaswordInputPopUp__label_16__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 255);
    lv_style_set_shadow_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__PaswordInputPopUp__AvailableNetworks2_1,
                     &GUI_Style__Button__PaswordInputPopUp__AvailableNetworks2_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__PaswordInputPopUp__image_10, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, &Font);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_15,
                     &GUI_Style__Label__PaswordInputPopUp__label_15__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                          lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_BOTTOM);
    lv_style_set_outline_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                               lv_color_make(3, 64, 34));
    lv_style_set_outline_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 255);
    lv_style_set_outline_pad(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_outline_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_shadow_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 255);
    lv_style_set_shadow_width(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__PaswordInputPopUp__AvailableNetworks3_1,
                     &GUI_Style__Button__PaswordInputPopUp__AvailableNetworks3_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__PaswordInputPopUp__image_8, &upload_frame_38_png);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, &Font);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_14,
                     &GUI_Style__Label__PaswordInputPopUp__label_14__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__Label_13,
                     &GUI_Style__Label__PaswordInputPopUp__Label_13__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT, lv_color_make(33, 31, 31));
    lv_style_set_bg_opa(&GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT, 173);
    lv_style_set_radius(&GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Panel__PaswordInputPopUp__panel_2, &GUI_Style__Panel__PaswordInputPopUp__panel_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__AutoMode_TIME_2,
                     &GUI_Style__Label__PaswordInputPopUp__AutoMode_TIME_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__PaswordInputPopUp__AutoMode_WIFI_image_2, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT, 15);
    lv_obj_add_style(GUI_Container__PaswordInputPopUp__container_15,
                     &GUI_Style__Container__PaswordInputPopUp__container_15__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, &Montserrat_24_500);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_75,
                     &GUI_Style__Label__PaswordInputPopUp__label_75__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT,
                        255);
    lv_style_set_radius(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT, 13);
    lv_obj_add_style(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button,
                     &GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, lv_color_make(227, 221, 218));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_77,
                     &GUI_Style__Label__PaswordInputPopUp__label_77__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT,
                          lv_color_make(244, 236, 229));
    lv_style_set_bg_opa(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT, 13);
    lv_obj_add_style(GUI_Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel,
                     &GUI_Style__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, 2);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, LV_TEXT_ALIGN_CENTER);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__label_76,
                     &GUI_Style__Label__PaswordInputPopUp__label_76__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, &Montserrat_10_600);
    lv_style_set_text_color(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, 1);
    lv_style_set_text_line_space(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__PaswordInputPopUp__Label_21,
                     &GUI_Style__Label__PaswordInputPopUp__Label_21__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT,
                          lv_color_make(244, 236, 229));
    lv_style_set_bg_opa(&GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT, 10);
    lv_obj_add_style(GUI_Textarea__PaswordInputPopUp__Textarea_4,
                     &GUI_Style__Textarea__PaswordInputPopUp__Textarea_4__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT,
                          lv_color_make(244, 244, 244));
    lv_style_set_bg_opa(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, 0);
    lv_style_set_text_color(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                     &GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT;
    lv_style_init(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, 10);
    lv_style_set_text_color(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                     &GUI_Style__Keyboard__PaswordInputPopUp__Keyboard__ITEMS_DEFAULT,
                     LV_PART_ITEMS | LV_STATE_DEFAULT);
}
