// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__Screen() {
    GUI_Screen__Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__Screen, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__Screen__Image_54 = lv_image_create(GUI_Screen__Screen);
    lv_obj_add_flag(GUI_Image__Screen__Image_54, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Screen__Image_54, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Screen__Image_54, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__Screen__Image_54, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Button__Screen__Button_2 = lv_button_create(GUI_Screen__Screen);
    lv_obj_set_align(GUI_Button__Screen__Button_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Screen__Button_2, 76, 85);
    lv_obj_set_size(GUI_Button__Screen__Button_2, 144, 42);
    lv_obj_add_event_cb(GUI_Button__Screen__Button_2, GUI_event__Button__Screen__Button_2__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Button__Screen__Button_1 = lv_button_create(GUI_Screen__Screen);
    lv_obj_set_align(GUI_Button__Screen__Button_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Screen__Button_1, -74, 85);
    lv_obj_set_size(GUI_Button__Screen__Button_1, 146, 44);
    lv_obj_add_event_cb(GUI_Button__Screen__Button_1, GUI_event__Button__Screen__Button_1__Clicked, LV_EVENT_CLICKED,
                        NULL);

    GUI_Label__Screen__Label_11 = lv_label_create(GUI_Screen__Screen);
    lv_label_set_long_mode(GUI_Label__Screen__Label_11, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Screen__Label_11, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Screen__Label_11, 74, 85);
    lv_obj_set_size(GUI_Label__Screen__Label_11, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Screen__Label_12 = lv_label_create(GUI_Screen__Screen);
    lv_label_set_long_mode(GUI_Label__Screen__Label_12, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Screen__Label_12, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Screen__Label_12, -77, 86);
    lv_obj_set_size(GUI_Label__Screen__Label_12, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Screen__container_23 = lv_obj_create(GUI_Screen__Screen);
    lv_obj_remove_style_all(GUI_Container__Screen__container_23);
    lv_obj_remove_flag(GUI_Container__Screen__container_23, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Screen__container_23, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Screen__container_23, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Screen__container_23, 317, -218);
    lv_obj_set_size(GUI_Container__Screen__container_23, 180, 44);

    GUI_Label__Screen__HOME_TIMEimage_2 = lv_label_create(GUI_Container__Screen__container_23);
    lv_label_set_long_mode(GUI_Label__Screen__HOME_TIMEimage_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Screen__HOME_TIMEimage_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Screen__HOME_TIMEimage_2, 42, -2);
    lv_obj_set_size(GUI_Label__Screen__HOME_TIMEimage_2, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Screen__HOME_WiFi_image_1 = lv_image_create(GUI_Container__Screen__container_23);
    lv_obj_add_flag(GUI_Image__Screen__HOME_WiFi_image_1, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Screen__HOME_WiFi_image_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Screen__HOME_WiFi_image_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Screen__HOME_WiFi_image_1, -12, -2);
    lv_obj_set_size(GUI_Image__Screen__HOME_WiFi_image_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__Screen();
    GUI_initScreenTexts__Screen();
}

void GUI_initScreenTexts__Screen() {
    lv_label_set_text_static(GUI_Label__Screen__Label_11, "Yes, stop");
    lv_label_set_text_static(GUI_Label__Screen__Label_12, "Cancel");
    lv_label_set_text_static(GUI_Label__Screen__HOME_TIMEimage_2, "16:44");
}

void GUI_initScreenStyles__Screen() {
    lv_image_set_src(GUI_Image__Screen__Image_54, &upload_dash_221_png);

    static lv_style_t GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT, 186);
    lv_style_set_radius(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT, 0);
    lv_style_set_bg_image_src(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT, &upload_dash_22_png);
    lv_style_set_bg_image_opa(&GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT, 255);
    lv_obj_add_style(GUI_Image__Screen__Image_54, &GUI_Style__Image__Screen__Image_54__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT, 13);
    lv_obj_add_style(GUI_Button__Screen__Button_2, &GUI_Style__Button__Screen__Button_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 13);
    lv_style_set_outline_color(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Screen__Button_1, &GUI_Style__Button__Screen__Button_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, lv_color_make(255, 255, 255));
    lv_style_set_text_opa(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Screen__Label_11, &GUI_Style__Label__Screen__Label_11__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Screen__Label_12, &GUI_Style__Label__Screen__Label_12__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Screen__HOME_TIMEimage_2, &GUI_Style__Label__Screen__HOME_TIMEimage_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Screen__HOME_WiFi_image_1, &upload_vector_i1_582_24x17_png);
}
