// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__Set_ParametersCustomMode() {
    GUI_Screen__Set_ParametersCustomMode = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__Set_ParametersCustomMode, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__Set_ParametersCustomMode__image_9 = lv_image_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_add_flag(GUI_Image__Set_ParametersCustomMode__image_9, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersCustomMode__image_9, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersCustomMode__image_9, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Image__Set_ParametersCustomMode__image_9, -1);
    lv_obj_set_size(GUI_Image__Set_ParametersCustomMode__image_9, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Set_ParametersCustomMode__container_12 = lv_obj_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersCustomMode__container_12);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__container_12, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__container_12, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersCustomMode__container_12, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersCustomMode__container_12, 299, -215);
    lv_obj_set_size(GUI_Container__Set_ParametersCustomMode__container_12, 122, 48);

    GUI_Label__Set_ParametersCustomMode__CustomMode_TIME =
        lv_label_create(GUI_Container__Set_ParametersCustomMode__container_12);
    lv_label_set_long_mode(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME, 29, -2);
    lv_obj_set_size(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI =
        lv_image_create(GUI_Container__Set_ParametersCustomMode__container_12);
    lv_obj_add_flag(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, -24, -4);
    lv_obj_set_size(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Set_ParametersCustomMode__Container_6 = lv_obj_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersCustomMode__Container_6);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersCustomMode__Container_6, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersCustomMode__Container_6, -365, -1);
    lv_obj_set_size(GUI_Container__Set_ParametersCustomMode__Container_6, 70, 482);

    GUI_Button__Set_ParametersCustomMode__Button_21 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_6);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_21, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_21, -2, -187);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_21, 74, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_21,
                        GUI_event__Button__Set_ParametersCustomMode__Button_21__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersCustomMode__Button_20 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_6);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_20, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_20, -1, -62);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_20, 76, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_20,
                        GUI_event__Button__Set_ParametersCustomMode__Button_20__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersCustomMode__Button_19 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_6);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_19, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_19, -1, 54);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_19, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_19,
                        GUI_event__Button__Set_ParametersCustomMode__Button_19__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersCustomMode__Button_18 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_6);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_18, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_18, -2, 182);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_18, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_18,
                        GUI_event__Button__Set_ParametersCustomMode__Button_18__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Container__Set_ParametersCustomMode__Container_9 = lv_obj_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersCustomMode__Container_9);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_9, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_9, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersCustomMode__Container_9, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersCustomMode__Container_9, -12, -159);
    lv_obj_set_size(GUI_Container__Set_ParametersCustomMode__Container_9, 328, 64);

    GUI_Button__Set_ParametersCustomMode__Button_23 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_9);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_23, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_23, 84, 3);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_23, 140, 40);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_23,
                        GUI_event__Button__Set_ParametersCustomMode__Button_23__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersCustomMode__Button_22 =
        lv_button_create(GUI_Container__Set_ParametersCustomMode__Container_9);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_22, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_22, -62, 2);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_22, 134, 38);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_22,
                        GUI_event__Button__Set_ParametersCustomMode__Button_22__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Container__Set_ParametersCustomMode__Container_13 = lv_obj_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_13, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersCustomMode__Container_13, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersCustomMode__Container_13, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersCustomMode__Container_13, -126, 11);
    lv_obj_set_size(GUI_Container__Set_ParametersCustomMode__Container_13, 354, 244);

    GUI_Textarea__Set_ParametersCustomMode__Textarea =
        lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea, -80, -52);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Textarea__Set_ParametersCustomMode__Textarea_1 =
    lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea_1, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea_1, -81, 11);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea_1, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea_1,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea_1__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Textarea__Set_ParametersCustomMode__Textarea_2 =
        lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea_2, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea_2, -81, 76);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea_2, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea_2,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea_2__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Textarea__Set_ParametersCustomMode__Textarea_3 =
        lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea_3, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea_3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea_3, 78, 76);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea_3, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea_3,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea_3__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Textarea__Set_ParametersCustomMode__Textarea_7 =
        lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea_7, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea_7, 79, -52);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea_7, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea_7,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea_7__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Textarea__Set_ParametersCustomMode__Textarea_8 =
        lv_textarea_create(GUI_Container__Set_ParametersCustomMode__Container_13);
    lv_textarea_set_text(GUI_Textarea__Set_ParametersCustomMode__Textarea_8, "");
    lv_obj_set_align(GUI_Textarea__Set_ParametersCustomMode__Textarea_8, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__Set_ParametersCustomMode__Textarea_8, 78, 11);
    lv_obj_set_size(GUI_Textarea__Set_ParametersCustomMode__Textarea_8, 152, 42);
    lv_obj_add_event_cb(GUI_Textarea__Set_ParametersCustomMode__Textarea_8,
                        GUI_event__Textarea__Set_ParametersCustomMode__Textarea_8__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersCustomMode__Button_24 = lv_button_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_set_align(GUI_Button__Set_ParametersCustomMode__Button_24, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersCustomMode__Button_24, 1, 193);
    lv_obj_set_size(GUI_Button__Set_ParametersCustomMode__Button_24, 226, 52);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersCustomMode__Button_24,
                        GUI_event__Button__Set_ParametersCustomMode__Button_24__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2 = lv_keyboard_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_remove_flag(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_keyboard_set_mode(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, LV_KEYBOARD_MODE_NUMBER);
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea);
    lv_obj_set_align(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, 218, 13);
    lv_obj_set_size(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2, 268, 234);
    lv_obj_add_event_cb(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                        GUI_event__Keyboard__Set_ParametersCustomMode__Keyboard_2__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Set_ParametersCustomMode__Image_14 = lv_image_create(GUI_Screen__Set_ParametersCustomMode);
    lv_obj_add_flag(GUI_Image__Set_ParametersCustomMode__Image_14, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersCustomMode__Image_14, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersCustomMode__Image_14, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Set_ParametersCustomMode__Image_14, -246, -170);
    lv_obj_set_size(GUI_Image__Set_ParametersCustomMode__Image_14, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__Set_ParametersCustomMode();
    GUI_initScreenTexts__Set_ParametersCustomMode();
}

void GUI_initScreenTexts__Set_ParametersCustomMode() {
    lv_label_set_text_static(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME, "16:44");
}

void GUI_initScreenStyles__Set_ParametersCustomMode() {
    lv_image_set_src(GUI_Image__Set_ParametersCustomMode__image_9, &upload_set_parametersmanual_png);

    static lv_style_t GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT);
    lv_style_set_border_color(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT,
                              lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 0);
    lv_style_set_pad_all(&GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__Set_ParametersCustomMode__image_9,
                     &GUI_Style__Image__Set_ParametersCustomMode__image_9__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersCustomMode__CustomMode_TIME,
                     &GUI_Style__Label__Set_ParametersCustomMode__CustomMode_TIME__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Set_ParametersCustomMode__CustomMode_WIFI, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                              lv_color_make(255, 193, 7));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                               lv_color_make(255, 193, 7));
    lv_style_set_outline_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_TOP);
    lv_style_set_pad_all(&GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT, 11);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_21,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_21__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_20,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_20__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_19,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_19__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_18,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_18__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT,
                              lv_color_make(255, 255, 255));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 1);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_23,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_23__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                          lv_color_make(219, 151, 1));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 5);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                              lv_color_make(255, 255, 255));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 2);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_22,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_22__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea_1,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea_2,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_2__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea_3,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_3__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea_7,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_7__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 5);
    lv_style_set_border_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 1);
    lv_style_set_border_side(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_text_color(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT, &Font_4);
    lv_obj_add_style(GUI_Textarea__Set_ParametersCustomMode__Textarea_8,
                     &GUI_Style__Textarea__Set_ParametersCustomMode__Textarea_8__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersCustomMode__Button_24,
                     &GUI_Style__Button__Set_ParametersCustomMode__Button_24__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT;
    lv_style_init(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT);
    lv_style_set_text_color(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                     &GUI_Style__Keyboard__Set_ParametersCustomMode__Keyboard_2__ITEMS_DEFAULT,
                     LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Set_ParametersCustomMode__Image_14, &upload_group_3_png);
}
