// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__Set_ParametersAutoMode() {
    GUI_Screen__Set_ParametersAutoMode = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__Set_ParametersAutoMode, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__Set_ParametersAutoMode__Image_57 = lv_image_create(GUI_Screen__Set_ParametersAutoMode);
    lv_obj_add_flag(GUI_Image__Set_ParametersAutoMode__Image_57, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersAutoMode__Image_57, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersAutoMode__Image_57, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__Set_ParametersAutoMode__Image_57, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Set_ParametersAutoMode__container_1 = lv_obj_create(GUI_Screen__Set_ParametersAutoMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersAutoMode__container_1);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__container_1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__container_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersAutoMode__container_1, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersAutoMode__container_1, 326, -209);
    lv_obj_set_size(GUI_Container__Set_ParametersAutoMode__container_1, 122, 48);

    GUI_Label__Set_ParametersAutoMode__AutoMode_TIME =
        lv_label_create(GUI_Container__Set_ParametersAutoMode__container_1);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME, 31, -4);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image =
        lv_image_create(GUI_Container__Set_ParametersAutoMode__container_1);
    lv_obj_add_flag(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, -24, -4);
    lv_obj_set_size(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Set_ParametersAutoMode__Container = lv_obj_create(GUI_Screen__Set_ParametersAutoMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersAutoMode__Container, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersAutoMode__Container, 36, 18);
    lv_obj_set_size(GUI_Container__Set_ParametersAutoMode__Container, 706, 424);

    GUI_Container__Set_ParametersAutoMode__Container_7 =
        lv_obj_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersAutoMode__Container_7);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container_7, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container_7, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersAutoMode__Container_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersAutoMode__Container_7, -35, -171);
    lv_obj_set_size(GUI_Container__Set_ParametersAutoMode__Container_7, 328, 64);

    GUI_Button__Set_ParametersAutoMode__Button_13 =
        lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_7);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_13, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_13, -71, -3);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_13, 140, 40);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_13,
                        GUI_event__Button__Set_ParametersAutoMode__Button_13__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersAutoMode__Button_8 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_7);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_8, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_8, 74, -4);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_8, 130, 34);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_8,
                        GUI_event__Button__Set_ParametersAutoMode__Button_8__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersAutoMode__Button_3 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_3, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_3, -239, -30);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_3, 114, 90);

    GUI_Button__Set_ParametersAutoMode__Button_4 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_4, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_4, -238, 68);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_4, 114, 90);

    GUI_Button__Set_ParametersAutoMode__Button_5 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_5, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_5, -103, 65);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_5, 114, 90);

    GUI_Button__Set_ParametersAutoMode__Button_6 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_6, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_6, -104, -28);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_6, 114, 90);

    GUI_Button__Set_ParametersAutoMode__Button_7 = lv_button_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_7, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_7, -37, 178);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_7, 226, 52);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_7,
                        GUI_event__Button__Set_ParametersAutoMode__Button_7__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Label__Set_ParametersAutoMode__Label_4 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_4, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_4, 58, -45);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_4, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Set_ParametersAutoMode__Label_6 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_6, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_6, 204, 99);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_6, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Set_ParametersAutoMode__Label_17 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_17, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_17, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_17, 202, 25);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_17, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Set_ParametersAutoMode__Label_18 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_18, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_18, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_18, 194, -44);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_18, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Set_ParametersAutoMode__Label_19 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_19, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_19, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_19, 65, 95);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_19, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__Set_ParametersAutoMode__Label_20 = lv_label_create(GUI_Container__Set_ParametersAutoMode__Container);
    lv_label_set_long_mode(GUI_Label__Set_ParametersAutoMode__Label_20, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__Set_ParametersAutoMode__Label_20, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Label__Set_ParametersAutoMode__Label_20, 60, 22);
    lv_obj_set_size(GUI_Label__Set_ParametersAutoMode__Label_20, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__Set_ParametersAutoMode__Container_4 = lv_obj_create(GUI_Screen__Set_ParametersAutoMode);
    lv_obj_remove_style_all(GUI_Container__Set_ParametersAutoMode__Container_4);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container_4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__Set_ParametersAutoMode__Container_4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__Set_ParametersAutoMode__Container_4, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__Set_ParametersAutoMode__Container_4, -363, 2);
    lv_obj_set_size(GUI_Container__Set_ParametersAutoMode__Container_4, 70, 482);

    GUI_Button__Set_ParametersAutoMode__Button_14 =
        lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_4);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_14, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_14, -2, -187);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_14, 74, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_14,
                        GUI_event__Button__Set_ParametersAutoMode__Button_14__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersAutoMode__Button_15 =
        lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_4);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_15, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_15, -1, -62);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_15, 76, 64);

    GUI_Button__Set_ParametersAutoMode__Button_16 =
        lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_4);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_16, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_16, -1, 54);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_16, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_16,
                        GUI_event__Button__Set_ParametersAutoMode__Button_16__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Button__Set_ParametersAutoMode__Button_17 =
        lv_button_create(GUI_Container__Set_ParametersAutoMode__Container_4);
    lv_obj_set_align(GUI_Button__Set_ParametersAutoMode__Button_17, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Button__Set_ParametersAutoMode__Button_17, -2, 182);
    lv_obj_set_size(GUI_Button__Set_ParametersAutoMode__Button_17, 70, 64);
    lv_obj_add_event_cb(GUI_Button__Set_ParametersAutoMode__Button_17,
                        GUI_event__Button__Set_ParametersAutoMode__Button_17__Clicked, LV_EVENT_CLICKED, NULL);

    GUI_Image__Set_ParametersAutoMode__Image_12 = lv_image_create(GUI_Screen__Set_ParametersAutoMode);
    lv_obj_add_flag(GUI_Image__Set_ParametersAutoMode__Image_12, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__Set_ParametersAutoMode__Image_12, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__Set_ParametersAutoMode__Image_12, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__Set_ParametersAutoMode__Image_12, -248, -170);
    lv_obj_set_size(GUI_Image__Set_ParametersAutoMode__Image_12, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__Set_ParametersAutoMode();
    GUI_initScreenTexts__Set_ParametersAutoMode();
}

void GUI_initScreenTexts__Set_ParametersAutoMode() {
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME, "16:44");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_4, "100");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_6, "100");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_17, "100");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_18, "100");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_19, "100");
    lv_label_set_text_static(GUI_Label__Set_ParametersAutoMode__Label_20, "100");
}

void GUI_initScreenStyles__Set_ParametersAutoMode() {
    static lv_style_t GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT);
    lv_style_set_bg_image_src(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, &upload_home_800x480_png);
    lv_style_set_bg_image_opa(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, 255);
    lv_style_set_text_color(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Screen__Set_ParametersAutoMode, &GUI_Style__Screen__Set_ParametersAutoMode__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Set_ParametersAutoMode__Image_57, &upload_home_800x480_png);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__AutoMode_TIME,
                     &GUI_Style__Label__Set_ParametersAutoMode__AutoMode_TIME__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Set_ParametersAutoMode__AutoMode_WIFI_image, &upload_vector_i1_582_24x17_png);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT,
                          lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT,
                              lv_color_make(255, 255, 255));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 1);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 1);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_13,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_13__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                          lv_color_make(219, 151, 1));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 5);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                              lv_color_make(255, 255, 255));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 2);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                               lv_color_make(0, 0, 0));
    lv_style_set_outline_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                              lv_color_make(219, 151, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_8,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_8__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_3,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_3__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_4,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_4__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_5,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_5__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_6,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_6__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 3);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT,
                              lv_color_make(3, 64, 34));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_7,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_7__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_4,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_4__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_6,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_6__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_17,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_17__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_18,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_18__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_19,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_19__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT, &Font_4);
    lv_style_set_text_color(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__Set_ParametersAutoMode__Label_20,
                     &GUI_Style__Label__Set_ParametersAutoMode__Label_20__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                              lv_color_make(255, 193, 7));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_outline_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                               lv_color_make(255, 193, 7));
    lv_style_set_outline_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 255);
    lv_style_set_outline_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_outline_pad(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_TOP);
    lv_style_set_pad_all(&GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT, 11);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_14,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_14__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_15,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_15__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_16,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_16__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT,
                          lv_color_make(255, 193, 7));
    lv_style_set_bg_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT,
                              lv_color_make(249, 172, 1));
    lv_style_set_border_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 2);
    lv_style_set_border_side(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_style_set_shadow_color(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT,
                              lv_color_make(158, 158, 158));
    lv_style_set_shadow_opa(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 128);
    lv_style_set_shadow_offset_x(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_style_set_shadow_offset_y(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_style_set_shadow_width(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_style_set_shadow_spread(&GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Button__Set_ParametersAutoMode__Button_17,
                     &GUI_Style__Button__Set_ParametersAutoMode__Button_17__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__Set_ParametersAutoMode__Image_12, &upload_group_3_png);
}
