// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_initScreen__SplashScreenLoadingPage() {
    GUI_Screen__SplashScreenLoadingPage = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__SplashScreenLoadingPage, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Image__SplashScreenLoadingPage__Splash_1 = lv_image_create(GUI_Screen__SplashScreenLoadingPage);
    lv_obj_remove_flag(GUI_Image__SplashScreenLoadingPage__Splash_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__SplashScreenLoadingPage__Splash_1, LV_ALIGN_CENTER);
    lv_obj_set_size(GUI_Image__SplashScreenLoadingPage__Splash_1, 800, 480);

    GUI_Image__SplashScreenLoadingPage__Image_19 = lv_image_create(GUI_Screen__SplashScreenLoadingPage);
    lv_obj_add_flag(GUI_Image__SplashScreenLoadingPage__Image_19, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__SplashScreenLoadingPage__Image_19, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Image__SplashScreenLoadingPage__Image_19, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Image__SplashScreenLoadingPage__Image_19, -55, -25);
    lv_obj_set_size(GUI_Image__SplashScreenLoadingPage__Image_19, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Textarea__SplashScreenLoadingPage__Textarea_5 = lv_textarea_create(GUI_Screen__SplashScreenLoadingPage);
    lv_textarea_set_text(GUI_Textarea__SplashScreenLoadingPage__Textarea_5, "Loading...");
    lv_obj_set_align(GUI_Textarea__SplashScreenLoadingPage__Textarea_5, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Textarea__SplashScreenLoadingPage__Textarea_5, 30, -21);
    lv_obj_set_size(GUI_Textarea__SplashScreenLoadingPage__Textarea_5, 150, 52);

    GUI_initScreenStyles__SplashScreenLoadingPage();
    GUI_initScreenTexts__SplashScreenLoadingPage();
}

void GUI_initScreenTexts__SplashScreenLoadingPage() {
}

void GUI_initScreenStyles__SplashScreenLoadingPage() {
    static lv_style_t GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT);
    lv_style_set_shadow_color(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_shadow_opa(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 255);
    lv_style_set_shadow_offset_x(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 5);
    lv_style_set_shadow_offset_y(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 5);
    lv_style_set_shadow_width(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 20);
    lv_style_set_shadow_spread(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_min_width(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 256);
    lv_style_set_transform_scale_y(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 256);
    lv_style_set_transform_rotation(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 0);
    lv_style_set_border_color(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_border_opa(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT, 3);
    lv_style_set_border_side(&GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT,
                             LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT | LV_BORDER_SIDE_TOP);
    lv_obj_add_style(GUI_Screen__SplashScreenLoadingPage, &GUI_Style__Screen__SplashScreenLoadingPage__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
    static lv_style_t GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT;
    lv_style_init(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT);
    lv_style_set_bg_image_src(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT, &img_template_png);
    lv_style_set_bg_image_opa(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT, 255);
    lv_style_set_bg_color(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT, lv_color_make(197, 141, 29));
    lv_style_set_bg_opa(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT, 0);
    lv_obj_add_style(GUI_Screen__SplashScreenLoadingPage,
                     &GUI_Style__Screen__SplashScreenLoadingPage__SCROLLBAR_DEFAULT,
                     LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__SplashScreenLoadingPage__Splash_1, &upload_splash_800x480_png);

    static lv_style_t GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__SplashScreenLoadingPage__Splash_1,
                     &GUI_Style__Image__SplashScreenLoadingPage__Splash_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__SplashScreenLoadingPage__Image_19, &upload_progress_indicator_png);

    static lv_style_t GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                          lv_color_make(255, 255, 255));
    lv_style_set_bg_opa(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 0);
    lv_style_set_radius(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 10);
    lv_style_set_text_font(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, &Font_2);
    lv_style_set_text_color(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                            lv_color_make(3, 64, 34));
    lv_style_set_text_opa(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_LEFT);
    lv_style_set_border_color(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                              lv_color_make(224, 224, 224));
    lv_style_set_border_opa(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 255);
    lv_style_set_border_width(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT, 0);
    lv_style_set_border_side(&GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                             LV_BORDER_SIDE_TOP | LV_BORDER_SIDE_RIGHT | LV_BORDER_SIDE_BOTTOM | LV_BORDER_SIDE_LEFT);
    lv_obj_add_style(GUI_Textarea__SplashScreenLoadingPage__Textarea_5,
                     &GUI_Style__Textarea__SplashScreenLoadingPage__Textarea_5__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
