// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#ifndef _GUI_H
#define _GUI_H

#include "core/gui_core.h"

#include "core/variables.h"

#include "helpers/ui_helpers.h"

LV_IMG_DECLARE(upload_manual_turn_png);
LV_FONT_DECLARE(Font_4);
LV_IMG_DECLARE(upload_vector_i1_582_24x17_png);
LV_IMG_DECLARE(img_template_png);
LV_IMG_DECLARE(upload_splash_800x480_png);
LV_IMG_DECLARE(upload_progress_indicator_png);
LV_FONT_DECLARE(Font_2);
LV_IMG_DECLARE(upload_dash_20_png);
LV_FONT_DECLARE(Font_1);
LV_FONT_DECLARE(Montserrat_24_500);
LV_IMG_DECLARE(upload_vector_i6_423_20x2250_png);
LV_IMG_DECLARE(upload_rectangle_11_png);
LV_FONT_DECLARE(Font_3);
LV_IMG_DECLARE(upload_vector_i10_426_2512x25_png);
LV_IMG_DECLARE(upload_vector_i7_437_30x2125_png);
LV_IMG_DECLARE(upload_vector_i7_431_2750x20_png);
LV_IMG_DECLARE(upload_vector_1_png);
LV_FONT_DECLARE(Montserrat17Medium);
LV_IMG_DECLARE(upload_group_3_png);
LV_IMG_DECLARE(upload_set_parametersmanual_png);
LV_IMG_DECLARE(upload_home_800x480_png);
LV_IMG_DECLARE(upload_cbi_chicken_png);
LV_IMG_DECLARE(upload_gameicons_plasticduck_png);
LV_IMG_DECLARE(upload_emojionemonotone_turkey_png);
LV_IMG_DECLARE(upload_cbi_chicken_1_png);
LV_IMG_DECLARE(upload_availablenetworks_png);
LV_IMG_DECLARE(upload_frame_38_png);
LV_FONT_DECLARE(Font);
LV_FONT_DECLARE(Montserrat_10_600);
LV_IMG_DECLARE(upload_vector_i10_420_20x2250_png);
LV_IMG_DECLARE(upload_si_warningfill_png);
LV_IMG_DECLARE(upload_dash_221_png);
LV_IMG_DECLARE(upload_dash_22_png);

#endif
