// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

#ifdef GUI_EXTERNAL_CUSTOM_CALLBACK_FUNCTION_FILE
#include GUI_EXTERNAL_CUSTOM_CALLBACK_FUNCTION_FILE
#endif

void GUI_event__Arc__MotorControl__arc_1__Clicked(lv_event_t *event) {
    lv_arc_set_value(GUI_Arc__MotorControl__arc_1, lv_arc_get_value(GUI_Arc__MotorControl__arc_1) + 25); // Arc_Increment
}

void GUI_event__Arc__MotorControl__arc__Clicked(lv_event_t *event) {
    lv_arc_set_value(GUI_Arc__MotorControl__arc, lv_arc_get_value(GUI_Arc__MotorControl__arc) + 25); // Arc_Increment
}

void GUI_event__Button__MotorControl__Button_32__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__MotorControl__Button_31__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__MotorControl__Button_30__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__MotorControl__Button_29__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MotorControl, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__MotorControl); // Change_Screen
}

void GUI_event__Button__MotorControl__Button_33__Clicked(lv_event_t *event) {
    lv_arc_set_value(GUI_Arc__MotorControl__arc, lv_arc_get_value(GUI_Arc__MotorControl__arc) + 25); // Arc_Increment
}

void GUI_event__Button__MotorControl__Button_34__Clicked(lv_event_t *event) {
    lv_arc_set_value(GUI_Arc__MotorControl__arc_1, lv_arc_get_value(GUI_Arc__MotorControl__arc_1) + 25); // Arc_Increment
}

void GUI_event__Button__Home__Home_HOME_button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__Home__Home_SET_PARAMETERS_button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__Home__Home_WIFI_button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__Home__Home_MOTORCONTROL_button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MotorControl, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__MotorControl); // Change_Screen
}

void GUI_event__Button__Home__Button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Screen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Screen); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_21__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_20__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_19__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_18__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MotorControl, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__MotorControl); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_23__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__Set_ParametersCustomMode__Button_22__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersCustomMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersCustomMode); // Change_Screen
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea); // Keyboard_Set_Target
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_1__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea_1); // Keyboard_Set_Target
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_2__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea_2); // Keyboard_Set_Target
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_3__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea_3); // Keyboard_Set_Target
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_7__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea_7); // Keyboard_Set_Target
}

void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_8__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__Set_ParametersCustomMode__Keyboard_2,
                             GUI_Textarea__Set_ParametersCustomMode__Textarea_8); // Keyboard_Set_Target
}

void GUI_event__Button__Set_ParametersCustomMode__Button_24__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Keyboard__Set_ParametersCustomMode__Keyboard_2__Clicked(lv_event_t *event) {
}

void GUI_event__Button__Set_ParametersAutoMode__Button_13__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersCustomMode, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0,
                      &GUI_initScreen__Set_ParametersCustomMode); // Change_Screen
}

void GUI_event__Button__Set_ParametersAutoMode__Button_8__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__Set_ParametersAutoMode__Button_7__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__AutoModePopUp, LV_SCR_LOAD_ANIM_NONE, 0, 0,
                      &GUI_initScreen__AutoModePopUp); // Change_Screen
}

void GUI_event__Button__Set_ParametersAutoMode__Button_14__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__Set_ParametersAutoMode__Button_16__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__Set_ParametersAutoMode__Button_17__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MotorControl, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__MotorControl); // Change_Screen
}

void GUI_event__Button__Available_Networks__AvailableNetworks1__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__PaswordInputPopUp, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__PaswordInputPopUp); // Change_Screen
}

void GUI_event__Button__Available_Networks__AvailableNetworks2__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__PaswordInputPopUp, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__PaswordInputPopUp); // Change_Screen
}

void GUI_event__Button__Available_Networks__AvailableNetworks3__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__PaswordInputPopUp, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__PaswordInputPopUp); // Change_Screen
}

void GUI_event__Button__Available_Networks__Button_28__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__Available_Networks__Button_27__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__Available_Networks__Button_26__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__Available_Networks__Button_25__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__MotorControl, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__MotorControl); // Change_Screen
}

void GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Available_Networks, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Available_Networks); // Change_Screen
}

void GUI_event__Textarea__PaswordInputPopUp__Textarea_4__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                             GUI_Textarea__PaswordInputPopUp__Textarea_4); // Keyboard_Set_Target
}

void GUI_event__Keyboard__PaswordInputPopUp__Keyboard__Clicked(lv_event_t *event) {
    lv_keyboard_set_textarea(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                             GUI_Textarea__PaswordInputPopUp__Textarea_4); // Keyboard_Set_Target
    lv_keyboard_set_textarea(GUI_Keyboard__PaswordInputPopUp__Keyboard,
                             GUI_Textarea__PaswordInputPopUp__Textarea_4); // Keyboard_Set_Target
}

void GUI_event__Button__AutoModePopUp__AutoModePopUp_StartButton__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__AutoModePopUp__AutoModePopUp_CancelButton__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersAutoMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersAutoMode); // Change_Screen
}

void GUI_event__Button__CustomModePopUp__CustomModePopUp_StartButton__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__CustomModePopUp__CustomModePopUp_CancelButton__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Set_ParametersCustomMode, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0,
                      &GUI_initScreen__Set_ParametersCustomMode); // Change_Screen
}

void GUI_event__Button__Screen__Button_2__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}

void GUI_event__Button__Screen__Button_1__Clicked(lv_event_t *event) {
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &GUI_initScreen__Home); // Change_Screen
}
