// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#include "../GUI.h"

void GUI_load() {
    GUI_initFramework();
    GUI_initHAL();
    GUI_loadContent();
}

void GUI_init() {
    GUI_loadContent();
}

void GUI_refresh() {
    lv_timer_handler();
    //...
}

void GUI_initHAL() {
    HAL_init();
}

void GUI_initFramework() {
    lv_init();
}

void GUI_loadContent() {
    GUI_initContent();
    GUI_loadFirstScreen();
}

void GUI_initContent() {
    GUI_initTheme();
    GUI_initScreens();
    GUI_initAnimations();
}

void GUI_initTheme() {
    lv_display_t *Display = lv_display_get_default();
    lv_theme_t *Theme = lv_theme_default_init(Display, lv_palette_main(LV_PALETTE_BLUE),
                                              lv_palette_main(LV_PALETTE_RED), false, lv_font_default());
    lv_display_set_theme(Display, Theme);
}

void GUI_initScreens() {
    GUI_initScreenContents();
}

void GUI_loadFirstScreen() {
    // Show the splash screen immediately...
    lv_screen_load(GUI_Screen__SplashScreenLoadingPage);
    // ...then, after exactly 10000 ms, fade into Home.
    // (Home is already initialized at this point by GUI_initScreenContents(),
    // so the target_init callback below is never actually invoked.)
    _ui_screen_change(&GUI_Screen__Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 2000, &GUI_initScreen__Home);
}

void GUI_initScreenContents() {
    GUI_initScreen__MotorControl();
    GUI_initScreen__SplashScreenLoadingPage();
    GUI_initScreen__Home();
    GUI_initScreen__Set_ParametersCustomMode();
    GUI_initScreen__Set_ParametersAutoMode();
    GUI_initScreen__Available_Networks();
    GUI_initScreen__PaswordInputPopUp();
    GUI_initScreen__AutoModePopUp();
    GUI_initScreen__CustomModePopUp();
    GUI_initScreen__Screen();
}

void GUI_initScreenTexts() {
    GUI_initScreenTexts__MotorControl();
    GUI_initScreenTexts__SplashScreenLoadingPage();
    GUI_initScreenTexts__Home();
    GUI_initScreenTexts__Set_ParametersCustomMode();
    GUI_initScreenTexts__Set_ParametersAutoMode();
    GUI_initScreenTexts__Available_Networks();
    GUI_initScreenTexts__PaswordInputPopUp();
    GUI_initScreenTexts__AutoModePopUp();
    GUI_initScreenTexts__CustomModePopUp();
    GUI_initScreenTexts__Screen();
}

void GUI_initScreenStyles() {
    GUI_initScreenStyles__MotorControl();
    GUI_initScreenStyles__SplashScreenLoadingPage();
    GUI_initScreenStyles__Home();
    GUI_initScreenStyles__Set_ParametersCustomMode();
    GUI_initScreenStyles__Set_ParametersAutoMode();
    GUI_initScreenStyles__Available_Networks();
    GUI_initScreenStyles__PaswordInputPopUp();
    GUI_initScreenStyles__AutoModePopUp();
    GUI_initScreenStyles__CustomModePopUp();
    GUI_initScreenStyles__Screen();
}
