// This file was generated by SquareLine Vision Exporter
// Project name: FabNest

#ifndef _GUI_CORE_H
#define _GUI_CORE_H

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Screen-specific function declarations
void GUI_initScreen__MotorControl();
void GUI_initScreenTexts__MotorControl();
void GUI_initScreenStyles__MotorControl();

void GUI_initScreen__SplashScreenLoadingPage();
void GUI_initScreenTexts__SplashScreenLoadingPage();
void GUI_initScreenStyles__SplashScreenLoadingPage();

void GUI_initScreen__Home();
void GUI_initScreenTexts__Home();
void GUI_initScreenStyles__Home();

void GUI_initScreen__Set_ParametersCustomMode();
void GUI_initScreenTexts__Set_ParametersCustomMode();
void GUI_initScreenStyles__Set_ParametersCustomMode();

void GUI_initScreen__Set_ParametersAutoMode();
void GUI_initScreenTexts__Set_ParametersAutoMode();
void GUI_initScreenStyles__Set_ParametersAutoMode();

void GUI_initScreen__Available_Networks();
void GUI_initScreenTexts__Available_Networks();
void GUI_initScreenStyles__Available_Networks();

void GUI_initScreen__PaswordInputPopUp();
void GUI_initScreenTexts__PaswordInputPopUp();
void GUI_initScreenStyles__PaswordInputPopUp();

void GUI_initScreen__AutoModePopUp();
void GUI_initScreenTexts__AutoModePopUp();
void GUI_initScreenStyles__AutoModePopUp();

void GUI_initScreen__CustomModePopUp();
void GUI_initScreenTexts__CustomModePopUp();
void GUI_initScreenStyles__CustomModePopUp();

void GUI_initScreen__Screen();
void GUI_initScreenTexts__Screen();
void GUI_initScreenStyles__Screen();

void GUI_load();

void GUI_init();

void GUI_refresh();

void GUI_initHAL();
void HAL_init();

void GUI_initFramework();

void GUI_loadContent();

void GUI_initContent();

void GUI_initTheme();

void GUI_initScreens();

void GUI_loadFirstScreen();

void GUI_initScreenContents();

void GUI_initScreenTexts();

void GUI_initScreenStyles();

void GUI_initAnimations();

void GUI_event__Arc__MotorControl__arc_1__Clicked(lv_event_t *event);
void GUI_event__Arc__MotorControl__arc__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_32__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_31__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_30__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_29__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_33__Clicked(lv_event_t *event);
void GUI_event__Button__MotorControl__Button_34__Clicked(lv_event_t *event);
void GUI_event__Button__Home__Home_HOME_button__Clicked(lv_event_t *event);
void GUI_event__Button__Home__Home_SET_PARAMETERS_button__Clicked(lv_event_t *event);
void GUI_event__Button__Home__Home_WIFI_button__Clicked(lv_event_t *event);
void GUI_event__Button__Home__Home_MOTORCONTROL_button__Clicked(lv_event_t *event);
void GUI_event__Button__Home__Button__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_21__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_20__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_19__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_18__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_23__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_22__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_1__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_2__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_3__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_7__Clicked(lv_event_t *event);
void GUI_event__Textarea__Set_ParametersCustomMode__Textarea_8__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersCustomMode__Button_24__Clicked(lv_event_t *event);
void GUI_event__Keyboard__Set_ParametersCustomMode__Keyboard_2__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_13__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_8__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_7__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_14__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_16__Clicked(lv_event_t *event);
void GUI_event__Button__Set_ParametersAutoMode__Button_17__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__AvailableNetworks1__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__AvailableNetworks2__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__AvailableNetworks3__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__Button_28__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__Button_27__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__Button_26__Clicked(lv_event_t *event);
void GUI_event__Button__Available_Networks__Button_25__Clicked(lv_event_t *event);
void GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Connect_Button__Clicked(lv_event_t *event);
void GUI_event__Button__PaswordInputPopUp__AvailableNetworksPopUp_Cancel__Clicked(lv_event_t *event);
void GUI_event__Textarea__PaswordInputPopUp__Textarea_4__Clicked(lv_event_t *event);
void GUI_event__Keyboard__PaswordInputPopUp__Keyboard__Clicked(lv_event_t *event);
void GUI_event__Button__AutoModePopUp__AutoModePopUp_StartButton__Clicked(lv_event_t *event);
void GUI_event__Button__AutoModePopUp__AutoModePopUp_CancelButton__Clicked(lv_event_t *event);
void GUI_event__Button__CustomModePopUp__CustomModePopUp_StartButton__Clicked(lv_event_t *event);
void GUI_event__Button__CustomModePopUp__CustomModePopUp_CancelButton__Clicked(lv_event_t *event);
void GUI_event__Button__Screen__Button_2__Clicked(lv_event_t *event);
void GUI_event__Button__Screen__Button_1__Clicked(lv_event_t *event);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
